// Actual authenticated API, PostgreSQL, browser charts and isolation. Local only.
import assert from 'node:assert/strict';
import { readFileSync, mkdirSync } from 'node:fs';
import { chromium } from 'playwright';
import AxeBuilder from '@axe-core/playwright';
import { createClient } from '@supabase/supabase-js';
import { scoreAttempt } from '../lib/assessment.ts';

const base = 'http://127.0.0.1:5173', text = readFileSync('.env.local', 'utf8');
assert.ok(text.startsWith('# Generated local QA configuration'));
const env = Object.fromEntries(text.split('\n').filter(line => line.includes('=')).map(line => [line.slice(0, line.indexOf('=')), line.slice(line.indexOf('=') + 1)]));
assert.match(env.NEXT_PUBLIC_SUPABASE_URL, /^http:\/\/(127\.0\.0\.1|localhost):\d+$/);
const db = createClient(env.NEXT_PUBLIC_SUPABASE_URL, env.SUPABASE_SERVICE_ROLE_KEY, { auth: { persistSession: false, autoRefreshToken: false } });
const browser = await chromium.launch({ executablePath: process.env.CHROMIUM_PATH || '/usr/bin/chromium' });
const created = { tests: [], cards: [], users: [] }; let tenantId, owner, originalBoard, hadBoard = false;
let checks = 0; const pass = name => { checks++; console.log('PASS:', name); };
const day = 86400000, now = Date.now(), stamp = crypto.randomUUID();
mkdirSync('test-results/analytics', { recursive: true });
async function session(email = 'recruiter@qa.invalid') { const context = await browser.newContext({ baseURL: base, viewport: { width: 1440, height: 1000 } }); assert.equal((await context.request.post('/auth/login', { data: { email, password: 'Local-QA-Only-57!Password' } })).status(), 200); return context; }
async function api(context, query = 'period=all', expected = 200) { const response = await context.request.get('/api/analytics?' + query); const value = await response.json(); assert.equal(response.status(), expected, JSON.stringify(value)); if (expected === 200) assert.match(response.headers()['cache-control'], /private, no-store/); return value; }
async function admin(context, value) { const response = await context.request.post('/api/admin', { data: value }); const data = await response.json(); assert.equal(response.status(), 200, JSON.stringify(data)); if (value.action === 'save' && !created.tests.includes(data.id)) created.tests.push(data.id); return data; }
async function audit(page, name) { await page.evaluate(async () => { await Promise.all(document.getAnimations().filter(animation => animation.playState === 'running' && Number.isFinite(animation.effect?.getComputedTiming().endTime)).map(animation => animation.finished.catch(() => {}))); }); const result = await new AxeBuilder({ page }).withTags(['wcag2a', 'wcag2aa', 'wcag21aa']).analyze(); assert.deepEqual(result.violations.map(v => ({ id: v.id, nodes: v.nodes.map(n => n.failureSummary) })), []); assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth + 1)); pass(name); }
async function showAnalytics(context) { const page = await context.newPage(); await page.goto('/'); await page.getByRole('button', { name: 'Analytics', exact: true }).click(); await page.getByRole('heading', { name: 'Analytics', exact: true }).waitFor(); await page.getByRole('button', { name: 'Refresh analytics', exact: true }).waitFor({ state: 'visible' }); await page.waitForFunction(() => !document.querySelector('[aria-label="Loading analytics"]')); return page; }
const modules = [
    { id: 'policy', kind: 'problem', title: 'Delivery policy', instructions: 'Apply the supplied policy.', seconds: 90, questions: [{ id: 'q1', prompt: 'The parcel is late. What do you do?', options: ['Investigate', 'Promise a refund'], correct: 0, explanation: 'PRIVATE ANSWER RATIONALE' }, { id: 'q2', prompt: 'Which step comes first?', options: ['Check the tracking', 'Contact a stranger'], correct: 0, explanation: 'PRIVATE SECOND ANSWER' }] },
    { id: 'type', kind: 'typing', title: 'Typing', seconds: 60, typingSeconds: 60, instructions: 'Type the passage.', typingMode: 'prefix-v1', passage: 'We are investigating your delivery and will give you an update tomorrow. We appreciate your patience and will check the tracking before providing further information.' },
    { id: 'write', kind: 'writing', title: 'Customer email', seconds: 180, instructions: 'Write a reply.', prompt: 'Explain the next step to the customer.', rubric: [{ id: 'policy', title: 'Policy accuracy', help: 'Use the provided policy', max: 3, anchors: ['Unsupported', 'Partial', 'Mostly accurate', 'Accurate'] }] },
];
const testData = (title, items = modules) => ({ id: '', title: 'QA SYNTHETIC Analytics ' + title + ' ' + stamp, description: '', status: 'ready', modules: items, updatedAt: 0, revision: 0 });
try {
    const unsigned = await browser.newContext({ baseURL: base }); await api(unsigned, 'period=all', 401); pass('Analytics are protected from signed-out visitors');
    const context = await session(), details = await (await context.request.get('/api/admin')).json(); owner = details.userId;
    const member = await db.from('workspace_members').select('tenant_id').eq('id', owner).single(); assert.ifError(member.error); tenantId = member.data.tenant_id;
    originalBoard = await (await context.request.get('/api/requests')).json(); hadBoard = !!originalBoard.revision;
    const empty = await api(context); assert.equal(empty.assessments.links, 0); assert.equal(empty.assessments.accuracy, null); pass('New workspaces show genuine empty metrics without seeded analytics');
    const emptyPage = await showAnalytics(context); assert.equal(await emptyPage.locator('.recharts-surface').count(), 0); assert.equal(await emptyPage.locator('.analytics-metric[aria-label="Objective accuracy"] > strong').textContent(), '—'); await audit(emptyPage, 'Empty analytics use readable unknown metrics without invented chart points'); await emptyPage.close();
    const testA = await admin(context, { action: 'save', assessment: testData('Support') }), testB = await admin(context, { action: 'save', assessment: testData('Policy only', [modules[0]]) });
    const attempt = (index, assessmentId = testA.id, items = modules, createdAt = now - day) => ({ id: crypto.randomUUID(), owner, tenant_id: tenantId, assessment_id: assessmentId, token_hash: crypto.randomUUID().replaceAll('-', '') + crypto.randomUUID().replaceAll('-', ''), alias: 'PRIVATE CANDIDATE ' + index, snapshot: { title: 'Assigned analytics test', modules: items }, status: 'not-started', created_at: createdAt, started_at: null, deadline: null, section_started_at: null, current_index: 0, answers: {}, result: null, review: null, expires_at: now + day, revoked: 0, demo: 0, revision: 1 });
    const historical = Array.from({ length: 1001 }, (_, i) => attempt('history-' + i, testA.id, modules, now - 60 * day));
    const completed = (index, items = modules, answers = { policy: { choices: { q1: 0, q2: 0 } }, type: { text: modules[1].passage, typing: { seconds: 60, complete: true } }, write: { text: 'PRIVATE CANDIDATE WRITING' } }, assessmentId = testA.id) => ({ ...attempt(index, assessmentId, items), status: 'completed', started_at: now - 180000, deadline: now, result: scoreAttempt(items, answers, now - 60000) });
    const reviewed = completed('reviewed'); reviewed.review = { outcome: 'reviewed', ratings: { 'write:policy': 3 }, notes: 'PRIVATE REVIEW NOTE', reviewedAt: now - 30000 };
    const interrupted = completed('interrupted', modules, { policy: { choices: { q1: 1, q2: 1 } }, type: { text: 'short', typing: { seconds: 10, interrupted: true, complete: false } } });
    const objectiveOnly = completed('no-writing', [modules[0]], { policy: { choices: { q1: 0, q2: 1 } } }, testB.id);
    const changed = structuredClone(modules); changed[0].questions[0].prompt += ' Policy revision 2'; changed[0].version = 2;
    const revised = completed('different-version', changed); revised.review = { outcome: 'not-scorable', ratings: { 'write:policy': 0 }, notes: '', reviewedAt: now };
    const active = attempt('active'); active.status = 'in-progress'; active.started_at = now; active.deadline = now + day;
    const expired = attempt('expired'); expired.expires_at = now - 1;
    const revoked = attempt('revoked'); revoked.revoked = 1;
    const notStarted = attempt('not-started');
    const recent = [reviewed, interrupted, objectiveOnly, revised, active, expired, revoked, notStarted];
    for (const batch of [historical.slice(0, 500), historical.slice(500), recent]) assert.ifError((await db.from('attempts').insert(batch)).error);
    const preview = completed('preview'); assert.ifError((await db.from('preview_attempts').insert(preview)).error);
    let all = await api(context); assert.equal(all.assessments.links, 1009); assert.equal(all.assessments.submitted, 4); assert.equal(all.assessments.awaiting, 1); assert.equal(all.assessments.typing.samples, 2); assert.equal(all.assessments.typing.excluded, 1); assert.equal(all.assessments.correct, 5); assert.equal(all.assessments.total, 8); assert.equal(all.assessments.accuracy, 62.5); pass('All-time analytics read beyond both the 200-record screen and 1000-row database limits');
    assert.equal(all.assessments.modules.filter(m => m.kind === 'problem').length, 2); assert.equal(all.assessments.writing[0].average, 3); assert.equal(all.assessments.writing[0].samples, 1); assert.equal(all.assessments.pipeline.reduce((sum, row) => sum + row.count, 0), 1009); pass('Assigned versions, review counts and objective results reconcile without preview contamination');
    for (const secret of ['PRIVATE CANDIDATE', 'PRIVATE ANSWER', 'PRIVATE REVIEW', 'token_hash', 'selectedId', 'optionOrder']) assert.ok(!JSON.stringify(all).includes(secret)); pass('Analytics payloads omit candidate identities, answer keys, responses and review notes');
    const thirty = await api(context, 'period=30'); assert.equal(thirty.assessments.links, 8); assert.equal(thirty.assessments.trend.reduce((sum, r) => sum + r.created, 0), 8);
    assert.equal((await api(context, 'period=all&assessment=' + testB.id)).assessments.links, 1); const dayDate = new Date(now - day).toISOString().slice(0, 10); assert.equal((await api(context, 'period=custom&from=' + dayDate + '&to=' + dayDate)).assessments.links, 8); pass('Date and assessment filters select the exact link cohort');
    const current = (await (await context.request.get('/api/admin')).json()).assessments.find(t => t.id === testA.id); current.modules[0].questions[0].prompt += ' Updated for future assignments'; await admin(context, { action: 'save', assessment: current }); const afterEdit = await api(context); assert.deepEqual(afterEdit.assessments.modules, all.assessments.modules); pass('Editing the reusable assessment does not rewrite assigned historical module analytics');
    for (const query of ['period=bogus', 'period=custom&from=2026-02-30&to=2026-03-01', 'view=nope']) await api(context, query, 400); await api(context, 'assessment=' + crypto.randomUUID(), 404); pass('Invalid dates and unknown assessments fail without silently changing the filter');
    assert.equal((await context.request.get('/api/analytics', { headers: { 'X-Tenant-Id': crypto.randomUUID() } })).status(), 409); pass('Stale business tabs cannot fetch a different tenant under the old selection');
    const second = await session('second@qa.invalid'); assert.equal((await api(second)).assessments.links, 0); await api(second, 'assessment=' + testA.id, 404); pass('Another business cannot see the first business aggregate or assessment names');
    const page = await showAnalytics(context), errors = []; page.on('pageerror', e => errors.push(e.message));
    assert.equal(await page.locator('.nav-count').textContent(), '1'); pass('The sidebar writing-review queue agrees with Analytics and excludes objective-only submissions');
    assert.equal(await page.locator('.analytics-metric[aria-label="Links created"] > strong').textContent(), '8'); assert.ok(await page.locator('.recharts-surface').count() >= 3); await audit(page, 'Desktop analytics charts and tables are accessible and fit');
    const chart = page.locator('.analytics-lines .recharts-surface'); await chart.focus(); await page.keyboard.press('ArrowRight'); await page.locator('.analytics-lines .recharts-tooltip-wrapper').waitFor({ state: 'visible' }); pass('Chart values can be inspected with keyboard arrow keys');
    const download = page.waitForEvent('download'); await page.getByRole('button', { name: 'Export CSV', exact: true }).click(); const downloaded = await download; let csv = ''; for await (const chunk of await downloaded.createReadStream()) csv += chunk.toString(); assert.ok(csv.includes('"Links created","8"')); assert.ok(csv.includes('"Objective accuracy (%)","62.5"')); assert.ok(!csv.includes('PRIVATE')); pass('CSV download matches active filters and excludes confidential source fields');
    let release; const gate = new Promise(resolve => { release = resolve; }); let intercepted; const started = new Promise(resolve => { intercepted = resolve; });
    const slow = async route => { if (new URL(route.request().url()).searchParams.get('period') === 'all') { const result = await route.fetch(); intercepted(); await gate; await route.fulfill({ response: result }).catch(() => {}); } else await route.continue(); };
    await page.route('**/api/analytics?**', slow); await page.getByLabel('Analytics date range').selectOption('all'); await started; assert.ok(await page.getByRole('button', { name: 'Export CSV', exact: true }).isDisabled()); await page.getByLabel('Analytics date range').selectOption('30'); await page.waitForFunction(() => document.querySelector('.analytics-metric[aria-label="Links created"] > strong')?.textContent === '8'); release(); await page.unroute('**/api/analytics?**', slow); await page.waitForFunction(() => !document.querySelector('[aria-label="Loading analytics"]')); assert.equal(await page.locator('.analytics-metric[aria-label="Links created"] > strong').textContent(), '8'); pass('Rapid filter changes cancel outdated responses and prevent exporting stale figures');
    await page.getByLabel('Analytics assessment', { exact: true }).selectOption(testB.id); await page.waitForFunction(() => document.querySelector('.analytics-metric[aria-label="Links created"] > strong')?.textContent === '1'); await page.getByRole('button', { name: 'Candidate review', exact: true }).click(); await page.getByRole('heading', { name: 'Candidate review', exact: true }).waitFor(); pass('Assessment selection updates charts and the candidate review shortcut works');
    await page.getByRole('button', { name: 'Analytics', exact: true }).click(); await page.getByRole('button', { name: 'Refresh analytics', exact: true }).waitFor();
    await page.getByLabel('Analytics date range').selectOption('custom'); await page.getByLabel('Analytics from date').fill(dayDate); await page.getByLabel('Analytics to date').fill(new Date(now - 2 * day).toISOString().slice(0, 10)); await page.getByRole('alert').waitFor(); assert.ok(await page.getByRole('button', { name: 'Export CSV', exact: true }).isDisabled()); await page.getByLabel('Analytics date range').selectOption('30'); await page.waitForFunction(() => !document.querySelector('[aria-label="Loading analytics"]') && document.querySelector('.analytics-metric')); pass('Filter errors show retry controls and disable stale exports');
    let failed = false; await page.route('**/api/analytics?**', async route => { if (!failed) { failed = true; await route.fulfill({ status: 503, contentType: 'application/json', body: JSON.stringify({ error: 'Temporary analytics failure' }) }); } else await route.continue(); }); await page.getByRole('button', { name: 'Refresh analytics', exact: true }).click(); await page.getByRole('alert').filter({ hasText: 'Temporary analytics failure' }).waitFor(); await page.getByRole('button', { name: 'Retry', exact: true }).click(); await page.waitForFunction(() => !!document.querySelector('.analytics-metric') && !document.querySelector('[role="alert"]')); await page.unroute('**/api/analytics?**'); pass('Failed analytics reads recover with Retry without showing stale figures');
    await page.screenshot({ path: 'test-results/analytics/desktop.png', fullPage: true });
    for (const [device, viewport] of [['mobile', { width: 390, height: 844 }], ['compact', { width: 320, height: 568 }]]) { await page.setViewportSize(viewport); await audit(page, device + ' analytics reflows without overflow'); await page.locator('.analytics-chart-data summary').first().click(); await audit(page, device + ' expanded chart data remains readable'); await page.locator('.analytics-chart-data summary').first().click(); if (device === 'mobile') await page.screenshot({ path: 'test-results/analytics/mobile.png', fullPage: true }); }
    const viewerEmail = 'analytics-viewer-' + stamp + '@qa.invalid'; const added = await db.auth.admin.createUser({ email: viewerEmail, password: 'Local-QA-Only-57!Password', email_confirm: true }); assert.ifError(added.error); created.users.push(added.data.user.id); assert.equal((await context.request.post('/api/accounts', { data: { action: 'add', email: viewerEmail, name: 'Analytics viewer', role: 'viewer' } })).status(), 200);
    const viewer = await session(viewerEmail); assert.equal((await api(viewer)).assessments.links, 1009); const viewerPage = await showAnalytics(viewer); await audit(viewerPage, 'Viewer analytics are accessible with the same protected aggregate'); assert.equal((await viewer.request.post('/api/analytics', { data: {} })).status(), 405); pass('Viewer can read analytics, while the endpoint exposes no mutation method');
    const board = await (await context.request.get('/api/requests')).json();
    const post = async value => { const response = await context.request.post('/api/requests', { headers: { 'X-Assess-Tenant': tenantId }, data: value }); const result = await response.json(); assert.equal(response.status(), 200, JSON.stringify(result)); return result; };
    await post({ action: 'columns', revision: board.revision, columns: [{ id: 'inbox', name: 'Customer requests' }, { id: 'qa-review', name: 'Quality review' }] });
    for (const [columnId, assigneeId, priority] of [['inbox', null, 'urgent'], ['qa-review', owner, 'normal'], ['inbox', owner, 'high']]) { const id = crypto.randomUUID(); created.cards.push(id); await post({ action: 'save', id, revision: 0, title: 'REQUESTS SYNTHETIC Analytics ' + id, description: '', columnId, assigneeId, priority }); }
    await post({ action: 'archive', id: created.cards[2], revision: 1 }); const requests = await api(context, 'view=requests&period=all'); assert.equal(requests.requests.created, 3); assert.equal(requests.requests.onBoard, 2); assert.equal(requests.requests.archived, 1); assert.equal(requests.requests.unassigned, 1); assert.equal(requests.requests.urgent, 1); assert.deepEqual(requests.requests.columns.map(c => c.name), ['Customer requests', 'Quality review']); assert.equal((await api(second, 'view=requests&period=all')).requests.onBoard, 0); pass('Requests use saved board columns, active assignment and archive counts with tenant isolation');
    await page.getByRole('tab', { name: 'Requests', exact: true }).click(); await page.waitForFunction(() => !!document.querySelector('.analytics-metric[aria-label="On board"]')); assert.equal(await page.locator('.analytics-metric[aria-label="On board"] > strong').textContent(), '2'); await audit(page, 'Requests analytics reflow on compact mobile'); await page.getByRole('button', { name: 'Requests board', exact: true }).click(); await page.getByRole('heading', { name: 'Requests', exact: true }).waitFor(); pass('Requests analytics tab and board shortcut work');
    const membership = await db.from('workspace_members').select('revision').eq('id', created.users[0]).single(); assert.equal((await context.request.post('/api/accounts', { data: { action: 'update', id: created.users[0], role: 'viewer', status: 'suspended', revision: membership.data.revision } })).status(), 200); await api(viewer, 'period=all', 401); pass('Suspension immediately removes analytics access from existing sessions');
    assert.deepEqual(errors, []); pass('Analytics journey has no browser runtime errors');
} finally {
    await browser.close();
    if (owner && created.tests.length) { for (const table of ['attempts', 'preview_attempts']) assert.ifError((await db.from(table).delete().eq('owner', owner).in('assessment_id', created.tests)).error); assert.ifError((await db.from('assessments').delete().eq('owner', owner).in('id', created.tests)).error); }
    if (tenantId && created.cards.length) assert.ifError((await db.from('workspace_requests').delete().eq('tenant_id', tenantId).in('id', created.cards)).error);
    if (tenantId && originalBoard) { if (hadBoard) assert.ifError((await db.from('request_boards').update({ columns: originalBoard.columns }).eq('tenant_id', tenantId)).error); else assert.ifError((await db.from('request_boards').delete().eq('tenant_id', tenantId)).error); }
    for (const id of created.users) { assert.ifError((await db.from('workspace_members').delete().eq('id', id)).error); assert.ifError((await db.auth.admin.deleteUser(id)).error); }
}
console.log(checks + ' analytics API/browser checks passed');
