import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {chromium} from 'playwright';
import AxeBuilder from '@axe-core/playwright';
const base='http://127.0.0.1:5173',browser=await chromium.launch({executablePath:'/usr/bin/chromium'}),admin=await browser.newContext(),guest=await browser.newContext();let checks=0;const pass=s=>{checks++;console.log('PASS:',s);};
async function api(c,path,body){const r=body?await c.request.post(base+path,{data:body}):await c.request.get(base+path);const d=await r.json();assert.equal(r.status(),200,JSON.stringify(d));return d;}
async function nav(page,name,width){if(width<768)await page.getByRole('button',{name:'Toggle Sidebar',exact:true}).click();await page.getByRole('button',{name,exact:true}).click();if(width<768)await page.keyboard.press('Escape');await page.getByRole('heading',{name,exact:true}).waitFor();}
async function audit(page){await page.evaluate(async()=>Promise.all(document.getAnimations().filter(a=>a.playState==='running'&&Number.isFinite(a.effect?.getComputedTiming().endTime)).map(a=>a.finished.catch(()=>{}))));const a=await new AxeBuilder({page}).withTags(['wcag2a','wcag2aa','wcag21aa']).analyze();assert.deepEqual(a.violations.map(v=>v.id),[]);assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));}
try{
 await api(admin,'/auth/login',{email:'recruiter@qa.invalid',password:'Local-QA-Only-57!Password'});
 for(const width of [1440,390,320]){
  const page=await admin.newPage();await page.setViewportSize({width,height:900});await page.goto(base);await nav(page,'Module library',width);await page.getByRole('button',{name:'Create module',exact:true}).click();await page.getByRole('dialog').getByRole('button',{name:'Questions',exact:true}).click();const title='BROWSER SYNTHETIC Answer keys '+width+' '+Date.now();await page.getByLabel('Module title',{exact:true}).fill(title);await page.getByLabel('Candidate instructions',{exact:true}).fill('Choose the answer supported by the case.');await page.getByLabel('Question',{exact:true}).fill('What should happen next?');await page.getByLabel('Question 1, option 1',{exact:true}).fill('Ignore the case.');await page.getByLabel('Question 1, option 2',{exact:true}).fill('Investigate the case.');await page.getByLabel('Correct answer for question 1',{exact:true}).selectOption('1');await page.getByLabel('Answer explanation',{exact:true}).fill('Investigate before making a promise.');await audit(page);await page.getByRole('tab',{name:'Scoring method',exact:true}).click();assert.equal(await page.getByLabel('Correct answer for question 1',{exact:true}).inputValue(),'1');await page.getByLabel('Correct answer for question 1',{exact:true}).selectOption('0');await page.getByLabel('Scoring explanation for question 1',{exact:true}).fill('Assessor-edited scoring explanation.');await audit(page);await page.getByRole('tab',{name:'Edit content',exact:true}).click();assert.equal(await page.getByLabel('Correct answer for question 1',{exact:true}).inputValue(),'0');await page.getByRole('button',{name:'Save module',exact:true}).click();await page.getByRole('heading',{name:'Module library',exact:true}).waitFor();let row=(await api(admin,'/api/admin')).library.find(r=>r.module.title===title);assert.equal(row.module.questions[0].correct,0);await page.reload();await nav(page,'Module library',width);await page.locator('.library-card').filter({hasText:title}).getByRole('button',{name:'Edit module',exact:true}).click();await page.getByRole('tab',{name:'Scoring method',exact:true}).click();assert.equal(await page.getByLabel('Correct answer for question 1',{exact:true}).inputValue(),'0');await page.getByLabel('Correct answer for question 1',{exact:true}).selectOption('1');await page.getByRole('button',{name:'Save module',exact:true}).click();await page.getByRole('heading',{name:'Module library',exact:true}).waitFor();row=(await api(admin,'/api/admin')).library.find(r=>r.id===row.id);assert.equal(row.module.questions[0].correct,1);pass(width+'px answer key edits agree across tabs, save, refresh and remain accessible');
  const bank=JSON.parse(readFileSync('content/customer-service-core-v1.json','utf8'));bank.title='BROWSER SYNTHETIC Scoring '+width;bank.modules=[row.module];bank.config={...bank.config,flexible:true,workSeconds:120,oneQuestionAtATime:false,allowBackNavigation:true};const saved=await api(admin,'/api/admin',{action:'save',assessment:bank});
  for(const choice of [1,0]){
   const link=await api(admin,'/api/admin',{action:'link',id:saved.id,alias:'BROWSER SYNTHETIC Scoring '+choice}),token=link.path.split('/').at(-1);let state=await api(guest,'/api/candidate?token='+token);assert.ok(!JSON.stringify(state).includes('correctOptionId'));state=await api(guest,'/api/candidate',{token,action:'start',revision:state.revision});assert.equal(state.module.questions[0].correct,undefined);assert.equal(state.module.questions[0].explanation,undefined);const qid=row.module.questions[0].id;await api(guest,'/api/candidate',{token,action:'submit',revision:state.revision,answer:{choices:{[qid]:choice}}});const attempt=(await api(admin,'/api/admin')).attempts.find(a=>a.id===link.id);assert.equal(attempt.result.objectiveCorrect,choice===1?1:0);assert.equal(attempt.result.objectiveTotal,1);
  }pass(width+'px assigned test scores the saved answer key; candidates never receive keys/explanations');await page.close();
 }
 const identityModule={id:crypto.randomUUID(),kind:'questions',title:'BROWSER SYNTHETIC Stable option identity '+Date.now(),seconds:120,instructions:'Choose the supported answer.',questions:[{id:crypto.randomUUID(),prompt:'Which action follows policy?',options:['First','Second','Third'],optionIds:['first','second','third'],correct:2,correctOptionId:'third',explanation:'Third follows the policy.'}]};const savedModule=await api(admin,'/api/admin',{action:'save-module',module:identityModule});const page=await admin.newPage();await page.goto(base);await nav(page,'Module library',1440);await page.locator('.library-card').filter({hasText:identityModule.title}).getByRole('button',{name:'Edit module',exact:true}).click();await page.getByLabel('Question 1, option 1',{exact:true}).fill('Second');await page.getByRole('button',{name:'Remove option 1',exact:true}).click();assert.equal(await page.getByLabel('Correct answer for question 1',{exact:true}).inputValue(),'1');await page.getByRole('button',{name:'Add answer option',exact:true}).click();await page.getByLabel('Question 1, option 3',{exact:true}).fill('New answer');await page.getByRole('button',{name:'Save module',exact:true}).click();await page.getByRole('heading',{name:'Module library',exact:true}).waitFor();const changed=(await api(admin,'/api/admin')).library.find(r=>r.id===savedModule.id).module.questions[0];assert.equal(changed.correctOptionId,'third');assert.deepEqual(changed.optionIds.slice(0,2),['second','third']);assert.equal(new Set(changed.optionIds).size,3);pass('Removing/adding options preserves the chosen stable answer identity, including temporarily matching text');
}finally{await browser.close();}
console.log(checks+' answer key checks passed');
