import { chromium } from 'playwright';
import AxeBuilder from '@axe-core/playwright';
import assert from 'node:assert/strict';
import { mkdirSync, writeFileSync } from 'node:fs';
const base = process.env.ASSESS_QA_BASE || 'http://127.0.0.1:5173';
assert.match(base, /^http:\/\/(127\.0\.0\.1|localhost):\d+$/);
mkdirSync('test-results', { recursive: true });
const results = [];
const record = (test, evidence = {}) => { results.push({ test, status: 'PASS', ...evidence }); writeFileSync('tests/browser-results.json', JSON.stringify(results, null, 2)); console.log(test); };
const browser = await chromium.launch(process.env.CHROMIUM_PATH ? { executablePath: process.env.CHROMIUM_PATH } : { executablePath: '/usr/bin/chromium' });
async function audit(page, name) {
    const report = await new AxeBuilder({ page }).withTags(['wcag2a', 'wcag2aa', 'wcag21aa']).analyze();
    assert.deepEqual(report.violations.map(v => ({ id: v.id, impact: v.impact, nodes: v.nodes.map(n => ({ target: n.target, summary: n.failureSummary })) })), [], name);
    record(name, { rulesPassed: report.passes.length });
}
async function noOverflow(page, name) { assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth + 1), name); record(name); }
async function navigate(page, name, mobile) {
    if (mobile) await page.getByRole('button', { name: 'Toggle Sidebar' }).click();
    await page.getByRole('button', { name: new RegExp(`^${name}(?:\\s*\\d+)?$`) }).click();
    if (mobile) await page.keyboard.press('Escape');
    await page.getByRole('heading', { name, exact: true }).waitFor();
}
try {
    for (const [device, viewport] of [['desktop', { width: 1440, height: 1000 }], ['mobile', { width: 390, height: 844 }]]) {
        const errors = [];
        const adminContext = await browser.newContext({ viewport });
        const page = await adminContext.newPage(); page.on('pageerror', e => errors.push(e.message));
        page.setDefaultTimeout(15000);
        await page.goto(base + '/login');
        await page.getByLabel('Email address', { exact: true }).fill('recruiter@qa.invalid');
        await page.getByLabel('Password', { exact: true }).fill('Local-QA-Only-57!Password');
        await audit(page, `${device} login accessibility`);
        await page.getByRole('button', { name: 'Sign in', exact: true }).click();
        await page.getByRole('heading', { name: 'Assessments', exact: true }).waitFor();
        const stamp = Date.now();
        const moduleTitle = `BROWSER SYNTHETIC ${device} Investigation ${stamp}`;
        const title = `BROWSER SYNTHETIC ${device} Assessment ${stamp}`;
        const alias = `BROWSER SYNTHETIC ${device} Applicant ${stamp}`;
        await navigate(page, 'Module library', device === 'mobile');
        await page.getByRole('button', { name: 'Create module', exact: true }).first().click();
        await page.getByRole('dialog').getByRole('button', { name: 'Investigation & policy', exact: true }).click();
        await page.getByLabel('Module title', { exact: true }).fill(moduleTitle);
        await page.getByLabel('Time limit (seconds)', { exact: true }).fill('90');
        await audit(page, `${device} module editor accessibility`);
        await noOverflow(page, `${device} module editor fits viewport`);
        await page.getByRole('button', { name: 'Save module', exact: true }).click();
        await page.getByRole('heading', { name: 'Module library', exact: true }).waitFor();
        let moduleCard = page.locator('.library-card').filter({ has: page.getByRole('heading', { name: moduleTitle, exact: true }) });
        await moduleCard.getByRole('button', { name: 'Edit module' }).click();
        await page.getByLabel('Module title', { exact: true }).fill(moduleTitle + ' saved');
        await page.getByRole('button', { name: 'Save module', exact: true }).click();
        await page.getByRole('heading', { name: 'Module library', exact: true }).waitFor();
        moduleCard = page.locator('.library-card').filter({ has: page.getByRole('heading', { name: moduleTitle + ' saved', exact: true }) });
        await moduleCard.getByRole('button', { name: 'Build assessment' }).click();
        await page.getByLabel('Assessment title', { exact: true }).fill(title);
        await page.getByRole('button', { name: 'Add module', exact: true }).click();
        const option = page.getByRole('dialog').locator('.add-module-choice').filter({ hasText: 'Written response' });
        await option.getByRole('button', { name: 'Use preset' }).click();
        await page.getByLabel('Time limit (seconds)', { exact: true }).fill('90');
        await page.getByRole('button', { name: 'Save & mark ready' }).click();
        await page.getByRole('heading', { name: 'Assessment builder', exact: true }).waitFor({ state: 'hidden' });
        await navigate(page, 'Assessments', device === 'mobile');
        let card = page.locator('.assessment-card').filter({ has: page.getByRole('heading', { name: title, exact: true }) });
        const before = (await (await page.request.get(base + '/api/admin')).json()).attempts.length;
        await card.getByRole('button', { name: 'Preview test' }).click();
        await page.getByText('Test preview · Your responses will not appear in candidate results.', { exact: true }).waitFor();
        assert.equal((await (await page.request.get(base + '/api/admin')).json()).attempts.length, before);
        record(`${device} Preview test creates no candidate record`);
        await page.goto(base + '/');await page.getByRole('heading', { name: 'Assessments', exact: true }).waitFor();
        card = page.locator('.assessment-card').filter({ has: page.getByRole('heading', { name: title, exact: true }) });
        await card.getByRole('button', { name: 'Create candidate link' }).click();
        await page.getByLabel('Candidate name or reference', { exact: true }).fill(alias);
        await page.getByRole('dialog').getByRole('button', { name: 'Create candidate link' }).click();
        const link = await page.getByLabel('Candidate assessment link', { exact: true }).inputValue();
        assert.match(link, /\/take\/[a-f0-9]{64}$/);await page.keyboard.press('Escape');
        record(`${device} create module → edit module → build assessment → generate link`);
        const candidateContext = await browser.newContext({ viewport });
        const candidate = await candidateContext.newPage();candidate.on('pageerror', e => errors.push(e.message));candidate.setDefaultTimeout(15000);
        assert.equal((await candidate.request.get(base + '/api/admin')).status(), 401);
        await candidate.goto(link);await candidate.getByRole('heading', { name: title, exact: true }).waitFor();
        await audit(candidate, `${device} signed-out candidate welcome accessibility`);
        await noOverflow(candidate, `${device} candidate welcome fits viewport`);
        await candidate.getByRole('checkbox').click();await candidate.getByRole('button', { name: 'Start assessment', exact: true }).click();
        await candidate.locator('.candidate-question').first().waitFor();
        for (const [i, choice] of [0, 2, 1].entries()) await candidate.locator('.candidate-question').nth(i).getByRole('radio').nth(choice).check();
        await candidate.waitForResponse(r => r.url().endsWith('/api/candidate') && r.request().method() === 'POST' && r.request().postDataJSON().action === 'save' && r.ok());
        const token = link.split('/').at(-1);
        const state = await (await candidate.request.get(base + '/api/candidate?token=' + token)).json();
        await candidate.reload();await candidate.locator('.candidate-question').first().waitFor();
        for (const [i, choice] of [0, 2, 1].entries()) assert.equal(await candidate.locator('.candidate-question').nth(i).getByRole('radio').nth(choice).isChecked(), true);
        const resumed = await (await candidate.request.get(base + '/api/candidate?token=' + token)).json();assert.equal(resumed.deadline, state.deadline);
        record(`${device} objective autosave and refresh preserve answers and timer`);
        await audit(candidate, `${device} objective questions accessibility`);
        await noOverflow(candidate, `${device} objective questions fit viewport`);
        await candidate.getByRole('button', { name: 'Save & continue', exact: true }).click();
        const reply = 'I understand that the delay has affected your gift. I will contact the courier now and update you within one working day. If the courier confirms that the parcel is lost, we can offer a replacement. You do not need to send any payment details.';
        await candidate.getByLabel('Your reply to the customer', { exact: true }).fill(reply);
        await candidate.waitForResponse(r => r.url().endsWith('/api/candidate') && r.request().method() === 'POST' && r.request().postDataJSON().action === 'save' && r.ok());
        await candidate.reload();await candidate.getByLabel('Your reply to the customer', { exact: true }).waitFor();assert.equal(await candidate.getByLabel('Your reply to the customer', { exact: true }).inputValue(), reply);
        await audit(candidate, `${device} written response accessibility`);
        await candidate.getByRole('button', { name: 'Submit assessment', exact: true }).click();
        await candidate.getByRole('alertdialog').getByRole('button', { name: 'Submit assessment', exact: true }).click();
        await candidate.getByRole('heading', { name: /You’re all done/ }).waitFor();
        await candidate.screenshot({ path: `test-results/${device}-candidate-complete.png`, fullPage: true });
        await candidate.reload();await candidate.getByRole('heading', { name: /You’re all done/ }).waitFor();
        const final = await (await candidate.request.get(base + '/api/candidate?token=' + token)).json();assert.equal(final.status, 'completed');assert.equal(final.module, null);assert.equal(final.result, undefined);
        record(`${device} signed-out writing autosave → refresh → submit → locked completion`);
        await navigate(page, 'Candidate review', device === 'mobile');
        await page.getByRole('button', { name: 'Refresh', exact: true }).click();
        await page.getByRole('textbox', { name: 'Search candidates' }).fill(alias);
        const row = page.getByRole('row').filter({ hasText: alias });
        await row.getByText('Awaiting review', { exact: true }).waitFor();
        await row.getByRole('button', { name: `Review ${alias}`, exact: true }).click();
        await page.getByText(reply, { exact: true }).waitFor();
        for (const criterion of ['Policy & accuracy', 'Empathy & tone', 'Clear writing', 'Ownership & next step']) await page.getByRole('radiogroup', { name: criterion, exact: true }).locator('.rating-choice').nth(4).click();
        const keyboardRating = page.getByRole('radiogroup', { name: 'Clear writing', exact: true }).getByRole('radio').nth(4); await keyboardRating.focus(); await keyboardRating.press('Space'); assert.equal(await keyboardRating.isChecked(), true);
        await page.getByLabel('Review notes & evidence', { exact: true }).fill('Accurately applies the investigation policy and gives a clear next-working-day update.');
        await audit(page, `${device} human-review accessibility`);
        await page.getByRole('button', { name: 'Save human review', exact: true }).click();
        await page.getByText(/Last reviewed/).waitFor();
        await page.screenshot({ path: `test-results/${device}-human-review.png`, fullPage: true });
        const stored = (await (await page.request.get(base + '/api/admin')).json()).attempts.find(a => a.alias === alias);
        assert.equal(stored.result.objective, 100);assert.deepEqual(Object.values(stored.review.ratings), [4,4,4,4]);
        record(`${device} saved objective result and human review are visible and persisted`);
        assert.deepEqual(errors, []);record(`${device} no browser runtime errors`);
        await candidateContext.close();await adminContext.close();
    }
} catch (error) {
    results.push({ test: 'BROWSER BLOCKER', status: 'FAIL', error: error.stack });writeFileSync('tests/browser-results.json', JSON.stringify(results, null, 2));throw error;
} finally { await browser.close(); }
