// All fixtures and writes are restricted to the generated loopback workspace.
import assert from 'node:assert/strict';
import {readFileSync,mkdirSync,writeFileSync} from 'node:fs';
import {chromium} from 'playwright';
import AxeBuilder from '@axe-core/playwright';
import {createClient} from '@supabase/supabase-js';
import {scoreAttempt} from '../lib/assessment.ts';
const base='http://127.0.0.1:5173',password='Local-QA-Only-57!Password';
const raw=readFileSync('.env.local','utf8');assert.ok(raw.startsWith('# Generated local QA configuration'));
const env=Object.fromEntries(raw.split('\n').filter(l=>l.includes('=')).map(l=>[l.slice(0,l.indexOf('=')),l.slice(l.indexOf('=')+1)]));assert.match(env.NEXT_PUBLIC_SUPABASE_URL,/^http:\/\/(127\.0\.0\.1|localhost):\d+$/);
const service=createClient(env.NEXT_PUBLIC_SUPABASE_URL,env.SUPABASE_SERVICE_ROLE_KEY,{auth:{persistSession:false,autoRefreshToken:false}}),browser=await chromium.launch({executablePath:process.env.CHROMIUM_PATH||'/usr/bin/chromium'});
const tracked={assessments:[],modules:[],attempts:[],users:[]},contexts=[],stamp=Date.now();let owner,tenant,checks=0;const pass=n=>{checks++;console.log('PASS:',n);};mkdirSync('test-results/candidate-tools',{recursive:true});
async function session(email='recruiter@qa.invalid',viewport={width:1440,height:1000}){const c=await browser.newContext({baseURL:base,viewport});contexts.push(c);assert.equal((await c.request.post('/auth/login',{data:{email,password}})).status(),200);return c;}
async function api(c,body,status=200,headers={}){const r=body?await c.request.post('/api/admin',{data:body,headers}):await c.request.get('/api/admin',{headers});const data=await r.json();assert.equal(r.status(),status,JSON.stringify(data));return data;}
async function audit(page,name){await page.evaluate(async()=>Promise.all(document.getAnimations().filter(a=>a.playState==='running'&&Number.isFinite(a.effect?.getComputedTiming().endTime)).map(a=>a.finished.catch(()=>{}))));const r=await new AxeBuilder({page}).withTags(['wcag2a','wcag2aa','wcag21aa']).analyze();assert.deepEqual(r.violations.map(v=>({id:v.id,nodes:v.nodes.map(n=>n.failureSummary)})),[]);assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));pass(name);}
async function nav(page,name,mobile=false){if(mobile)await page.getByRole('button',{name:'Toggle Sidebar',exact:true}).click();await page.getByRole('button',{name,exact:true}).click();if(mobile)await page.keyboard.press('Escape');await page.getByRole('heading',{name,exact:true}).waitFor();}
async function saved(page,button){const response=page.waitForResponse(r=>r.url().endsWith('/api/admin')&&r.request().method()==='POST'&&r.ok());await page.getByRole('button',{name:button,exact:true}).click();await response;}
const q={id:crypto.randomUUID(),kind:'questions',title:'Policy decision',seconds:120,instructions:'Use the facts.',questions:[{id:crypto.randomUUID(),prompt:'PRIVATE POLICY QUESTION',options:['Investigate','Promise delivery'],correct:0,explanation:'PRIVATE KEY'}]};
const typing={id:crypto.randomUUID(),kind:'typing',title:'Typing passage',seconds:60,instructions:'Copy the text.',typingMode:'prefix-v1',typingSeconds:30,passage:'The customer needs a factual update. Inspect the dispatch history and tracking events, record the next action, and keep the investigation open until the courier replies.'};
const writing={id:crypto.randomUUID(),kind:'writing',title:'Written update',seconds:120,instructions:'Write the update.',prompt:'PRIVATE WRITING PROMPT',rubric:[{id:crypto.randomUUID(),title:'Factual accuracy',help:'Use the facts.',max:2,anchors:['Invents facts','Some evidence','Accurate and complete']}]};
try{
 const c=await session(),state=await api(c);owner=state.userId;tenant=(await service.from('workspace_members').select('tenant_id').eq('id',owner).single()).data.tenant_id;
 const assessment={id:'',title:'QA SYNTHETIC Candidate tools '+stamp,description:'',status:'ready',modules:[q,typing,writing],revision:0,updatedAt:0,config:{flexible:true,workSeconds:300,introductionSeconds:0,code:'CUSTOM-TOOLS',supportEmail:'',toolPolicy:'',notice:'',spellCheck:true,oneQuestionAtATime:false,allowBackNavigation:true}};
 const original=await api(c,{action:'save',assessment});tracked.assessments.push(original.id);const library=await api(c,{action:'save-module',module:q});tracked.modules.push(library.id);
 const modified=structuredClone(assessment);modified.title+=' Alternate';modified.modules[0].questions[0].prompt='DIFFERENT POLICY QUESTION';modified.config.workSeconds=420;const other=await api(c,{action:'save',assessment:modified});tracked.assessments.push(other.id);
 const candidates=[];
 for(const [i,id]of [original.id,original.id,other.id,original.id,original.id].entries()){
  const link=await api(c,{action:'link',id,alias:i===0?'=EXPORT Candidate '+stamp:'QA SYNTHETIC Tools candidate '+i+' '+stamp});tracked.attempts.push(link.id);candidates.push(link);
  if(i<3){const row=(await service.from('attempts').select('snapshot').eq('id',link.id).single()).data,snapshot=row.snapshot,answers={};for(const m of snapshot.modules){if(m.questions)answers[m.id]={choices:{[m.questions[0].id]:i===1?1:0}};else if(m.kind==='typing')answers[m.id]={text:i===1?'Wrong text':'The customer',typing:{seconds:30,complete:true,startedAt:stamp,deadline:stamp+30000}};else answers[m.id]={text:'PRIVATE WRITTEN RESPONSE'};}const result=scoreAttempt(snapshot.modules,answers,stamp+1000);const review={ratings:{[writing.id+':'+writing.rubric[0].id]:i===1?0:2},evidence:{[writing.id+':'+writing.rubric[0].id]:'Evidence from response'},notes:'PRIVATE REVIEW NOTES',outcome:'reviewed',reviewedAt:stamp+1000};assert.ifError((await service.from('attempts').update({answers,result,review,status:'completed',started_at:stamp,deadline:stamp+300000}).eq('id',link.id)).error);}
 }
 const initial=(await api(c)).attempts.find(a=>a.id===candidates[0].id);assert.equal(initial.hiring.stage,'Unassigned');
 await api(c,{action:'hiring',id:initial.id,hiring:{stage:'Trial shift',notes:'PRIVATE HIRING NOTES',revision:0}});const decision=(await api(c)).attempts.find(a=>a.id===initial.id);assert.equal(decision.hiring.stage,'Trial shift');assert.equal(decision.revision,initial.revision);assert.deepEqual(decision.result,initial.result);assert.deepEqual(decision.answers,initial.answers);assert.deepEqual(decision.modules,initial.modules);assert.deepEqual(decision.review,initial.review);pass('Hiring decisions persist without changing response revisions, snapshots, answers or scoring');
 await api(c,{action:'hiring',id:initial.id,hiring:{stage:'Interview',notes:'Stale overwrite',revision:0}},409);assert.equal((await api(c)).attempts.find(a=>a.id===initial.id).hiring.notes,'PRIVATE HIRING NOTES');pass('Separate hiring revision protects edits from stale tabs');
 for(const hiring of [{stage:'',notes:'',revision:1},{stage:'x'.repeat(51),notes:'',revision:1},{stage:'Interview',notes:'x'.repeat(5001),revision:1},{stage:'Interview',notes:'',revision:-1},{stage:'Interview',notes:'',revision:'1'}])await api(c,{action:'hiring',id:initial.id,hiring},400);pass('Invalid stage names, note lengths and revisions are rejected');
 const unsigned=await browser.newContext({baseURL:base});contexts.push(unsigned);await api(unsigned,null,401);await api(unsigned,{action:'hiring',id:initial.id,hiring:{stage:'Hired',notes:'',revision:1}},401);
 const signedOut=await unsigned.request.get('/api/candidate?token='+candidates[3].path.split('/').at(-1));const publicState=await signedOut.json();assert.equal(publicState.hiring,undefined);assert.ok(!JSON.stringify(publicState).includes('PRIVATE HIRING NOTES'));pass('Candidate bearer links expose no hiring decisions or notes');
 await api(c,{action:'hiring',id:candidates[3].id,hiring:{stage:'Interview',notes:'First call scheduled',revision:0}});const started=await unsigned.request.post('/api/candidate',{data:{token:candidates[3].path.split('/').at(-1),action:'start',revision:publicState.revision,hiring:{stage:'Hired',notes:'FORGED'}}});assert.equal(started.status(),200);const running=await started.json();assert.equal(running.status,'in-progress');assert.equal((await api(c)).attempts.find(a=>a.id===candidates[3].id).hiring.stage,'Interview');pass('Hiring edits and candidate progress use independent revisions; candidate metadata forgery is ignored');
 await api(c,{action:'hiring',id:initial.id,hiring:{stage:'Hired',notes:'',revision:1}},409,{'x-tenant-id':crypto.randomUUID()});await api(c,{action:'hiring',id:initial.id,hiring:{stage:'Hired',notes:'',revision:1}},403,{Origin:'https://foreign.invalid'});pass('Stale business headers and foreign origins cannot change hiring metadata');
 const foreign=await session('second@qa.invalid');assert.ok(!(await api(foreign)).attempts.some(a=>a.id===initial.id));await api(foreign,{action:'hiring',id:initial.id,hiring:{stage:'Hired',notes:'',revision:1}},404);pass('Other businesses cannot discover or edit candidates');
 for(const role of ['editor','viewer']){const email=`tools-${role}-${stamp}@qa.invalid`,u=await service.auth.admin.createUser({email,password,email_confirm:true});assert.ifError(u.error);tracked.users.push(u.data.user.id);assert.equal((await c.request.post('/api/accounts',{data:{action:'add',email,name:'QA '+role,role}})).status(),200);}
 const editor=await session(`tools-editor-${stamp}@qa.invalid`),viewer=await session(`tools-viewer-${stamp}@qa.invalid`);await api(editor,{action:'hiring',id:initial.id,hiring:{stage:'Trial shift',notes:'PRIVATE HIRING NOTES from editor',revision:1}});await api(viewer,{action:'hiring',id:initial.id,hiring:{stage:'Hired',notes:'',revision:2}},403);pass('Editors can save hiring notes; Viewers can read but cannot change them');
 const viewerDb=createClient(env.NEXT_PUBLIC_SUPABASE_URL,env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY,{auth:{persistSession:false,autoRefreshToken:false}});assert.ifError((await viewerDb.auth.signInWithPassword({email:`tools-viewer-${stamp}@qa.invalid`,password})).error);const denied=await viewerDb.from('attempts').update({hiring:{stage:'Hired',notes:'Bypass',revision:3}}).eq('id',initial.id).select('id');assert.ok(denied.error||denied.data.length===0);assert.equal((await api(c)).attempts.find(a=>a.id===initial.id).hiring.stage,'Trial shift');pass('Database RLS independently blocks Viewer hiring updates');
 assert.ifError((await service.from('workspace_members').update({status:'suspended'}).eq('id',tracked.users[0])).error);await api(editor,{action:'hiring',id:initial.id,hiring:{stage:'Hired',notes:'',revision:2}},401);pass('Suspension blocks previously signed-in editors');
 const pages=[];for(let i=0;i<1003;i++){const id=crypto.randomUUID();pages.push({id,owner,tenant_id:tenant,assessment_id:original.id,token_hash:crypto.randomUUID().replaceAll('-','')+crypto.randomUUID().replaceAll('-',''),alias:'QA SYNTHETIC Pagination '+i,snapshot:assessment,status:'not-started',created_at:stamp-10000,answers:{},demo:0,revision:1,expires_at:stamp+86400000,revoked:0});tracked.attempts.push(id);}
 for(let i=0;i<pages.length;i+=250)assert.ifError((await service.from('attempts').insert(pages.slice(i,i+250))).error);const all=await api(c);assert.equal(all.attempts.filter(a=>pages.some(p=>p.id===a.id)).length,1003);assert.equal(new Set(all.attempts.map(a=>a.id)).size,all.attempts.length);pass('Candidate reads include over 1,000 records and tied timestamps without gaps or duplicates');for(let i=0;i<pages.length;i+=100)assert.ifError((await service.from('attempts').delete().eq('owner',owner).in('id',pages.slice(i,i+100).map(p=>p.id))).error);
 const page=await c.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('/');await page.getByRole('heading',{name:'Assessments',exact:true}).waitFor();
 await page.getByRole('button',{name:'More actions for '+assessment.title,exact:true}).click();await page.getByRole('menuitem',{name:'Duplicate assessment',exact:true}).click();assert.equal(await page.getByLabel('Assessment title',{exact:true}).inputValue(),assessment.title+' (copy)');await page.getByLabel('Assessment title',{exact:true}).fill('QA SYNTHETIC Duplicate assessment '+stamp);await saved(page,'Save draft');await page.getByRole('heading',{name:'Assessments',exact:true}).waitFor();let current=await api(c),copy=current.assessments.find(a=>a.title==='QA SYNTHETIC Duplicate assessment '+stamp);tracked.assessments.push(copy.id);const source=current.assessments.find(a=>a.id===original.id);assert.equal(copy.status,'draft');assert.notEqual(copy.id,source.id);assert.notEqual(copy.modules[0].id,source.modules[0].id);assert.notEqual(copy.modules[0].questions[0].id,source.modules[0].questions[0].id);assert.deepEqual(copy.config,source.config);assert.deepEqual(source.modules,initial.modules);pass('Duplicate assessments become separate editable drafts with new module/question IDs');
 await nav(page,'Module library');await page.getByLabel('Search modules',{exact:true}).fill(q.title);assert.equal(await page.locator('.library-card').count(),1);await page.getByRole('button',{name:'More actions for '+q.title,exact:true}).click();await page.getByRole('menuitem',{name:'Duplicate module',exact:true}).click();assert.equal(await page.getByLabel('Module title',{exact:true}).inputValue(),q.title+' (copy)');await page.getByLabel('Module title',{exact:true}).fill('QA SYNTHETIC Duplicate module '+stamp);await page.getByLabel('Question 1, option 1',{exact:true}).fill('Investigate the dispatch history');await saved(page,'Save module');await page.getByRole('heading',{name:'Module library',exact:true}).waitFor();current=await api(c);const moduleCopy=current.library.find(r=>r.module.title==='QA SYNTHETIC Duplicate module '+stamp);tracked.modules.push(moduleCopy.id);assert.notEqual(moduleCopy.module.id,q.id);assert.equal(current.library.find(r=>r.id===library.id).module.questions[0].options[0],'Investigate');assert.deepEqual(current.attempts.find(a=>a.id===initial.id).modules,initial.modules);await page.getByLabel('Search modules',{exact:true}).fill('no matching module');await page.getByText('No modules match this view',{exact:true}).waitFor();await page.getByLabel('Search modules',{exact:true}).fill('');await page.getByLabel('Module type filter',{exact:true}).click();await page.getByRole('option',{name:'Typing',exact:true}).click();assert.equal(await page.locator('.library-card').count(),0);pass('Library search/type filters work and duplicated module edits preserve originals and issued links');
 await nav(page,'Candidate review');await page.getByLabel('Assessment filter',{exact:true}).click();await page.getByRole('option',{name:assessment.title,exact:true}).click();await page.waitForFunction(()=>document.querySelectorAll('table[aria-label="Candidates"] tbody tr').length===4);assert.equal(await page.locator('table[aria-label="Candidates"] tbody tr').count(),4);
 await page.getByRole('button',{name:'Review '+initial.alias,exact:true}).click();assert.equal(await page.getByLabel('Hiring notes',{exact:true}).inputValue(),'PRIVATE HIRING NOTES from editor');await page.getByLabel('Hiring stage',{exact:true}).click();await page.getByRole('option',{name:'Custom stage…',exact:true}).click();await page.getByLabel('Custom hiring stage',{exact:true}).fill('Paid trial');await page.getByLabel('Hiring notes',{exact:true}).fill('PRIVATE HIRING NOTES assessor follow-up');await saved(page,'Save hiring decision');await page.getByText(/Updated /).waitFor();await page.getByRole('button',{name:'Close',exact:true}).click();await page.reload();await nav(page,'Candidate review');await page.getByLabel('Hiring stage filter',{exact:true}).click();await page.getByRole('option',{name:'Paid trial',exact:true}).click();await page.waitForFunction(()=>document.querySelectorAll('table[aria-label="Candidates"] tbody tr').length===1);assert.equal(await page.locator('table[aria-label="Candidates"] tbody tr').count(),1);pass('Custom hiring stages and private notes survive refresh and filter the candidate list');
 const download=page.waitForEvent('download');await page.getByRole('button',{name:'Export CSV',exact:true}).click();const downloaded=await download,csv=readFileSync(await downloaded.path(),'utf8');assert.ok(csv.includes('"\'=EXPORT Candidate '+stamp+'"'));assert.ok(csv.includes('Paid trial'));assert.ok(csv.includes('Correct-character WPM'));assert.ok(!csv.includes('QA SYNTHETIC Tools candidate 1'));for(const privateText of ['PRIVATE HIRING NOTES','PRIVATE POLICY QUESTION','PRIVATE WRITTEN RESPONSE','PRIVATE KEY',candidates[0].path.split('/').at(-1)])assert.ok(!csv.includes(privateText));pass('Filtered CSV exports scoring evidence, escapes formulas and excludes private content and bearer links');
 await page.getByLabel('Hiring stage filter',{exact:true}).click();await page.getByRole('option',{name:'All hiring stages',exact:true}).click();for(const id of [0,1]){const a=(await api(c)).attempts.find(a=>a.id===candidates[id].id);await page.getByLabel('Compare '+a.alias,{exact:true}).check();}await page.getByRole('button',{name:'Compare (2/4)',exact:true}).click();const comparison=page.getByRole('dialog',{name:'Compare candidates',exact:true});await comparison.waitFor();assert.equal(await comparison.getByText('Different assessment content or settings',{exact:true}).count(),0);assert.ok((await comparison.innerText()).includes('1 of 1 · 100%'));assert.ok((await comparison.innerText()).includes('0 of 1 · 0%'));assert.ok((await comparison.innerText()).includes('2 / 2'));await audit(page,'Desktop comparison is accessible and fits the viewport');await page.screenshot({path:'test-results/candidate-tools/desktop-comparison.png',fullPage:true});await comparison.getByRole('button',{name:'Close',exact:true}).click();
 const alternate=(await api(c)).attempts.find(a=>a.id===candidates[2].id);await page.getByLabel('Compare '+alternate.alias,{exact:true}).check();await page.getByRole('button',{name:'Compare (3/4)',exact:true}).click();await page.getByText('Different assessment content or settings',{exact:true}).waitFor();await page.getByRole('dialog').getByRole('button',{name:'Close',exact:true}).click();pass('Comparison separates objective, typing and human evidence and flags differing assigned content');
 const fourth=(await api(c)).attempts.find(a=>a.id===candidates[3].id),fifth=(await api(c)).attempts.find(a=>a.id===candidates[4].id);await page.getByLabel('Compare '+fourth.alias,{exact:true}).check();assert.ok(await page.getByLabel('Compare '+fifth.alias,{exact:true}).isDisabled());await page.getByRole('button',{name:'Compare (4/4)',exact:true}).click();assert.equal(await page.locator('.comparison-candidate').count(),4);await audit(page,'Four-candidate comparison stays accessible');await page.getByRole('dialog').getByRole('button',{name:'Close',exact:true}).click();
 for(const [name,viewport]of [['mobile',{width:390,height:844}],['compact',{width:320,height:568}]]){await page.setViewportSize(viewport);await audit(page,name+' candidate filters and selection fit the viewport');await page.getByRole('button',{name:'Compare (4/4)',exact:true}).click();await audit(page,name+' comparison fits without horizontal scroll');await page.screenshot({path:'test-results/candidate-tools/'+name+'-comparison.png',fullPage:true});await page.getByRole('dialog').getByRole('button',{name:'Close',exact:true}).click();await page.getByRole('button',{name:'Review '+initial.alias,exact:true}).click();await audit(page,name+' hiring notes and review are accessible');await page.getByRole('button',{name:'Close',exact:true}).click();}
 const vp=await viewer.newPage();await vp.goto('/');await nav(vp,'Candidate review');await vp.getByRole('button',{name:'Review '+initial.alias,exact:true}).click();assert.ok(await vp.getByLabel('Hiring notes',{exact:true}).isDisabled());assert.equal(await vp.getByRole('button',{name:'Save hiring decision',exact:true}).count(),0);await vp.getByRole('button',{name:'Close',exact:true}).click();for(const i of [0,1]){const a=(await api(c)).attempts.find(a=>a.id===candidates[i].id);await vp.getByLabel('Compare '+a.alias,{exact:true}).check();}await vp.getByRole('button',{name:'Compare (2/4)',exact:true}).click();await vp.getByRole('dialog',{name:'Compare candidates',exact:true}).waitFor();await vp.getByRole('dialog').getByRole('button',{name:'Close',exact:true}).click();assert.ok(await vp.getByRole('button',{name:'Export CSV',exact:true}).isEnabled());await nav(vp,'Assessments');assert.equal(await vp.getByRole('button',{name:/More actions for/}).count(),0);pass('Viewers can compare and export results while editing and duplication remain protected');assert.deepEqual(errors,[]);pass('New candidate workflows have no browser runtime errors');
}finally{
 writeFileSync('.runtime/candidate-tools-fixtures.json',JSON.stringify({owner,...tracked}),{mode:0o600});
 for(const table of ['preview_attempts','attempts','assessments','modules']){const ids=table==='preview_attempts'?tracked.assessments:tracked[table];for(let i=0;i<ids.length;i+=100){const r=await service.from(table).delete().eq('owner',owner).in(table==='preview_attempts'?'assessment_id':'id',ids.slice(i,i+100));assert.ifError(r.error);}}
 for(const id of tracked.users){assert.ifError((await service.from('workspace_members').delete().eq('id',id)).error);assert.ifError((await service.auth.admin.deleteUser(id)).error);}
 for(const c of contexts)await c.close();await browser.close();
}
console.log(checks+' candidate tools checks passed; exact fixtures removed.');
