import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {randomBytes} from 'node:crypto';
import {createClient} from '@supabase/supabase-js';
import {chromium} from 'playwright';
import AxeBuilder from '@axe-core/playwright';
const base='http://127.0.0.1:5173';
const env=Object.fromEntries(readFileSync('.env.local','utf8').split('\n').filter(l=>l.includes('=')).map(l=>[l.slice(0,l.indexOf('=')),l.slice(l.indexOf('=')+1)]));
assert.match(env.NEXT_PUBLIC_SUPABASE_URL,/^http:\/\/(127\.0\.0\.1|localhost):\d+$/);
const db=createClient(env.NEXT_PUBLIC_SUPABASE_URL,env.SUPABASE_SERVICE_ROLE_KEY,{auth:{persistSession:false,autoRefreshToken:false}}),anon=createClient(env.NEXT_PUBLIC_SUPABASE_URL,env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY,{auth:{persistSession:false,autoRefreshToken:false}});
const browser=await chromium.launch({executablePath:'/usr/bin/chromium'}),admin=await browser.newContext(),other=await browser.newContext(),guest=await browser.newContext();
let id,checks=0;const pass=s=>{checks++;console.log('PASS:',s);},newToken=()=>randomBytes(32).toString('hex');
async function api(context,path,body,status=200,headers={}){const r=body?await context.request.post(base+path,{data:body,headers}):await context.request.get(base+path,{headers});const d=await r.json();assert.equal(r.status(),status,JSON.stringify(d));return d;}
async function audit(page,name){await page.evaluate(async()=>Promise.all(document.getAnimations().filter(a=>a.playState==='running'&&Number.isFinite(a.effect?.getComputedTiming().endTime)).map(a=>a.finished.catch(()=>{}))));const r=await new AxeBuilder({page}).withTags(['wcag2a','wcag2aa','wcag21aa']).analyze();assert.deepEqual(r.violations.map(v=>v.id),[]);assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));pass(name);}
try{
 await api(admin,'/auth/login',{email:'recruiter@qa.invalid',password:'Local-QA-Only-57!Password'});await api(other,'/auth/login',{email:'second@qa.invalid',password:'Local-QA-Only-57!Password'});
 const bank=JSON.parse(readFileSync('content/customer-service-core-v1.json','utf8')),test=structuredClone(bank);test.id='';test.revision=0;test.title='BROWSER SYNTHETIC General links '+Date.now();test.modules=[test.modules[0],test.modules[3]];test.modules[0].questions=test.modules[0].questions.slice(0,2);test.config.flexible=true;test.config.workSeconds=300;
 id=(await api(admin,'/api/admin',{action:'save',assessment:test})).id;
 await api(guest,'/api/admin',{action:'general-link',id},401);await api(other,'/api/admin',{action:'general-link',id},404);pass('General link creation requires the right signed-in workspace');
 const link=await api(admin,'/api/admin',{action:'general-link',id}),token=link.path.split('/').at(-1);
 const before=await api(admin,'/api/admin');assert.equal(before.attempts.filter(a=>a.assessmentId===id).length,0);assert.ok(before.generalLinks.some(a=>a.id===link.id&&a.path===link.path));pass('Reusable link is retrievable and creates no candidate until registration');
 const intro=await api(guest,'/api/general-link?token='+token);assert.deepEqual(Object.keys(intro).sort(),['description','seconds','title']);await api(guest,'/api/candidate?token='+token,undefined,404);pass('Public link exposes no answers, answer keys or candidate records');
 assert.equal((await anon.from('general_links').select('*')).error?.code,'42501');assert.ok((await anon.rpc('register_general_candidate',{link_token:token,candidate_name:'Forged',attempt_hash:newToken()})).error);pass('Anonymous database access and direct registration RPC are denied');
 await api(guest,'/api/general-link',{token,name:' ',attemptToken:newToken()},400);await api(guest,'/api/general-link',{token,name:'A'.repeat(81),attemptToken:newToken()},400);await api(guest,'/api/general-link',{token,name:'Bad\nName',attemptToken:newToken()},400);await api(guest,'/api/general-link',{token,name:'Name',attemptToken:'weak'},400);await api(guest,'/api/general-link',{token,name:'Name',attemptToken:newToken()},403,{Origin:'https://foreign.invalid'});pass('Name, private token and request-origin validation');
 const retryToken=newToken(),registration={token,name:'Same name',attemptToken:retryToken};const retries=await Promise.all(Array.from({length:5},()=>api(guest,'/api/general-link',registration)));assert.ok(retries.every(r=>r.path===retries[0].path));let rows=(await api(admin,'/api/admin')).attempts.filter(a=>a.assessmentId===id);assert.equal(rows.length,1);assert.equal(rows[0].status,'not-started');assert.equal(rows[0].startedAt,null);pass('Concurrent retry and duplicate clicks create one attempt without starting the timer');
 const otherToken=newToken();await api(guest,'/api/general-link',{token,name:'Same name',attemptToken:otherToken});rows=(await api(admin,'/api/admin')).attempts.filter(a=>a.assessmentId===id);assert.equal(rows.length,2);assert.notEqual(rows[0].id,rows[1].id);pass('Different people with the same name receive separate attempts');
 const original=(await api(guest,'/api/candidate?token='+retryToken));await api(admin,'/api/admin',{action:'save',assessment:{...before.assessments.find(a=>a.id===id),title:'BROWSER SYNTHETIC Changed general link '+Date.now()}});assert.equal((await api(guest,'/api/general-link?token='+token)).title,test.title);assert.equal(original.title,test.title);pass('General links retain their issued assessment and scoring snapshot');
 for(const width of [1440,390,320]){
  const context=await browser.newContext({viewport:{width,height:width===320?568:900}}),page=await context.newPage();await page.goto(base+link.path);await page.getByLabel('Your name',{exact:true}).waitFor();await audit(page,width+'px signed-out name entry accessibility and reflow');assert.ok(await page.getByRole('button',{name:'Continue',exact:true}).isDisabled());await page.getByLabel('Your name',{exact:true}).fill('Applicant '+width);
  if(width===320){let lost=false;await page.route('**/api/general-link',async route=>{if(route.request().method()==='POST'&&!lost){lost=true;await route.fetch();await route.abort();}else await route.continue();});await page.getByRole('button',{name:'Continue',exact:true}).click();await page.getByRole('alert').waitFor();await page.reload();await page.getByLabel('Your name',{exact:true}).fill('Applicant '+width);pass('Lost registration response survives refresh and retry');}
  await page.getByRole('button',{name:'Continue',exact:true}).click();await page.waitForURL('**/take/*');await page.getByRole('button',{name:'Start assessment',exact:true}).waitFor();const attempt=page.url().split('/').at(-1),welcome=await api(context,'/api/candidate?token='+attempt);assert.equal(welcome.alias,'Applicant '+width);assert.equal(welcome.status,'not-started');await audit(page,width+'px private candidate welcome');
  await page.getByText('I’m ready to start',{exact:true}).click();await page.getByRole('button',{name:'Start assessment',exact:true}).click();for(let i=0;i<2;i++){const q=test.modules[0].questions[i];await page.getByRole('radiogroup',{name:q.prompt,exact:true}).getByText(q.options[q.correct],{exact:true}).click();if(i===0){await page.getByRole('button',{name:'Next question',exact:true}).click();await page.getByRole('radiogroup',{name:test.modules[0].questions[1].prompt,exact:true}).waitFor();await page.reload();await page.getByRole('radiogroup',{name:test.modules[0].questions[1].prompt,exact:true}).waitFor();}}
  await page.getByRole('button',{name:'Save & continue',exact:true}).click();await page.getByLabel('Your reply to the customer',{exact:true}).fill('Hello, I have checked your order and will arrange the next step.');await page.getByRole('button',{name:'Submit assessment',exact:true}).click();await page.getByRole('alertdialog').getByRole('button',{name:'Confirm submission',exact:true}).click();await page.getByRole('heading',{name:'Your responses have been submitted',exact:true}).waitFor();await page.reload();await page.getByRole('heading',{name:'Your responses have been submitted',exact:true}).waitFor();const saved=(await api(admin,'/api/admin')).attempts.find(a=>a.alias==='Applicant '+width&&a.assessmentId===id);assert.equal(saved.status,'completed');assert.equal(saved.result.objectiveCorrect,2);assert.equal(saved.result.objectiveTotal,2);assert.ok(saved.answers[test.modules[1].id].text);assert.equal((await api(context,'/api/candidate?token='+otherToken)).status,'not-started');pass(width+'px name → one-question test → refresh → submit → separate saved result');await page.goto(base+link.path);await page.getByLabel('Your name',{exact:true}).fill('Next person '+width);await page.getByRole('button',{name:'Continue',exact:true}).click();await page.waitForURL('**/take/*');assert.notEqual(page.url().split('/').at(-1),attempt);assert.equal((await api(context,'/api/candidate?token='+attempt)).status,'completed');pass(width+'px reopening general link on a shared device gives the next person a new attempt');await context.close();
 }
 const page=await admin.newPage();for(const width of [1440,390,320]){await page.setViewportSize({width,height:width===320?568:900});await page.goto(base);const row=page.locator('.assessment-table tbody tr').filter({hasText:'Changed general link'});await row.getByRole('button',{name:'General links',exact:true}).click();await page.getByRole('dialog').waitFor();await audit(page,width+'px general-link management dialog');assert.ok(await page.getByRole('button',{name:'Copy link',exact:true}).count());await page.keyboard.press('Escape');}
 await api(other,'/api/admin',{action:'close-general-link',id:link.id},404);await api(admin,'/api/admin',{action:'close-general-link',id:link.id});await api(guest,'/api/general-link?token='+token,undefined,404);await api(guest,'/api/general-link',{token,name:'Late candidate',attemptToken:newToken()},404);assert.equal((await api(guest,'/api/candidate?token='+retryToken)).status,'not-started');pass('Closing a link blocks new candidates while existing private attempts remain usable');
 const exp=await api(admin,'/api/admin',{action:'general-link',id});await db.from('general_links').update({expires_at:Date.now()-1}).eq('id',exp.id);await api(guest,'/api/general-link?token='+exp.path.split('/').at(-1),undefined,404);pass('Expired general links refuse registration');
 const userDb=createClient(env.NEXT_PUBLIC_SUPABASE_URL,env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY,{auth:{persistSession:false,autoRefreshToken:false}});await userDb.auth.signInWithPassword({email:'second@qa.invalid',password:'Local-QA-Only-57!Password'});assert.deepEqual((await userDb.from('general_links').select('*').eq('id',link.id)).data,[]);assert.ok((await userDb.rpc('register_general_candidate',{link_token:token,candidate_name:'Forged',attempt_hash:newToken()})).error);pass('Other businesses cannot read general links or call the registration RPC');
}finally{if(id){for(const table of ['attempts','preview_attempts','general_links']){const {error}=await db.from(table).delete().eq('assessment_id',id);assert.ifError(error);}assert.ifError((await db.from('assessments').delete().eq('id',id)).error);}await browser.close();}
console.log(checks+' general link checks passed');
