import assert from 'node:assert/strict';
import {readFileSync,mkdirSync} from 'node:fs';
import {chromium} from 'playwright';
import AxeBuilder from '@axe-core/playwright';
const base='http://127.0.0.1:5173',browser=await chromium.launch({executablePath:'/usr/bin/chromium'});mkdirSync('.runtime/mobile-after',{recursive:true});let checks=0;const pass=s=>{checks++;console.log('PASS:',s);};
async function audit(page,name){await page.evaluate(async()=>Promise.all(document.getAnimations().filter(a=>a.playState==='running'&&Number.isFinite(a.effect?.getComputedTiming().endTime)).map(a=>a.finished.catch(()=>{}))));assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),'Page reflow: '+name);const report=await new AxeBuilder({page}).withTags(['wcag2a','wcag2aa','wcag21aa']).analyze();assert.deepEqual(report.violations.map(v=>({id:v.id,nodes:v.nodes.map(n=>n.failureSummary)})),[],name);const badInputs=await page.locator('input:not([type=checkbox]):not([type=radio]),select,textarea').evaluateAll(ns=>ns.filter(n=>n.getBoundingClientRect().width&&parseFloat(getComputedStyle(n).fontSize)<16).map(n=>n.getAttribute('aria-label')));assert.deepEqual(badInputs,[],name+' readable form inputs');pass(name+' accessibility, readable fields and page reflow');}
async function dialogBounds(page){const dialog=page.getByRole('dialog').last();const b=await dialog.boundingBox(),height=await page.evaluate(()=>innerHeight);assert.ok(b.y>=0&&b.y+b.height<=height+1,'Dialog must fit the viewport');const close=dialog.getByRole('button',{name:'Close',exact:true});if(await close.count()){const box=await close.boundingBox();assert.ok(box.width>=44&&box.height>=44);}return dialog;}
try{for(const viewport of [{width:320,height:568},{width:390,height:844},{width:667,height:375},{width:768,height:1024}]){
 const c=await browser.newContext({baseURL:base,viewport,hasTouch:true,isMobile:true}),page=await c.newPage();assert.equal((await c.request.post('/auth/login',{data:{email:'recruiter@qa.invalid',password:'Local-QA-Only-57!Password'}})).status(),200);
 async function nav(name){await page.goto('/');if(viewport.width<768)await page.getByRole('button',{name:'Toggle Sidebar',exact:true}).click();await page.getByRole('button',{name,exact:true}).click();if(viewport.width<768)await page.keyboard.press('Escape');await page.getByRole('heading',{name,exact:true}).waitFor();}
 for(const name of ['Assessments','Module library','Candidate review','Requests','Analytics','Accounts & permissions']){await nav(name);await audit(page,viewport.width+'px '+name);const small=await page.locator('button[data-slot=button],a[data-slot=button],button[data-slot=tabs-trigger]').evaluateAll(ns=>ns.filter(n=>{const r=n.getBoundingClientRect();return r.width&&r.height&&r.height<43.9;}).map(n=>n.textContent));assert.deepEqual(small,[],name+' touch controls');
  if(name==='Requests'){
   await page.getByRole('button',{name:'New request',exact:true}).click();await audit(page,viewport.width+'px request form');const dialog=await dialogBounds(page);await dialog.getByRole('button',{name:'Save request',exact:true}).scrollIntoViewIfNeeded();assert.ok((await dialog.getByRole('button',{name:'Save request',exact:true}).boundingBox()).y>=0);await page.keyboard.press('Escape');await page.getByRole('button',{name:'Edit columns',exact:true}).click();await audit(page,viewport.width+'px column editing');await dialogBounds(page);await page.keyboard.press('Escape');
  }
  if(name==='Accounts & permissions'){
   await page.getByRole('button',{name:'Add account',exact:true}).click();await audit(page,viewport.width+'px account form');const dialog=await dialogBounds(page);await dialog.getByRole('button',{name:'Create account',exact:true}).scrollIntoViewIfNeeded();const b=await dialog.getByRole('button',{name:'Create account',exact:true}).boundingBox();assert.ok(b.y>=0&&b.y+b.height<=await page.evaluate(()=>innerHeight));await page.keyboard.press('Escape');
  }
 }
 await nav('Module library');await page.getByRole('button',{name:'Create module',exact:true}).click();await page.getByRole('dialog').getByRole('button',{name:'Questions',exact:true}).click();await audit(page,viewport.width+'px module editor');if(viewport.width<768){const rejected=page.waitForResponse(r=>r.url().endsWith('/api/admin')&&r.request().method()==='POST'&&r.request().postDataJSON()?.action==='save-module');await page.getByRole('button',{name:'Save module',exact:true}).click();assert.equal((await rejected).status(),400);await page.locator('[data-sonner-toast][data-type=error][data-mounted=true]').waitFor();await page.evaluate(async()=>Promise.all(document.getAnimations().filter(a=>a.playState==='running'&&Number.isFinite(a.effect?.getComputedTiming().endTime)).map(a=>a.finished.catch(()=>{}))));const toast=await page.locator('[data-sonner-toast][data-type=error]').boundingBox(),save=await page.getByRole('button',{name:'Save module',exact:true}).boundingBox();assert.ok(toast.y+toast.height<=save.y,'Validation messages must not cover the save bar');pass(viewport.width+'px validation notice leaves save controls reachable');}for(const name of ['Edit content','Candidate preview','Scoring method']){const tab=page.getByRole('tab',{name,exact:true});await tab.scrollIntoViewIfNeeded();const b=await tab.boundingBox();assert.ok(b.x>=0&&b.x+b.width<=await page.evaluate(()=>innerWidth));await tab.click();}await page.getByRole('tab',{name:'Edit content',exact:true}).click();await page.getByLabel('Answer explanation',{exact:true}).scrollIntoViewIfNeeded();if(viewport.width<768){const save=await page.getByRole('button',{name:'Save module',exact:true}).boundingBox();assert.ok(save.y>=0&&save.y+save.height<=await page.evaluate(()=>innerHeight),'Save stays reachable at the end of the form');}await page.screenshot({path:'.runtime/mobile-after/'+viewport.width+'-module.png',fullPage:true});
 await page.goto('/');const bank=JSON.parse(readFileSync('content/customer-service-core-v1.json','utf8'));bank.title='BROWSER SYNTHETIC Mobile layout '+viewport.width+' '+Date.now();const r=await c.request.post('/api/admin',{data:{action:'save',assessment:bank}});assert.equal(r.status(),200);await page.reload();await page.locator('.assessment-table tbody tr').filter({hasText:bank.title}).getByRole('button',{name:'Edit assessment',exact:true}).click();await audit(page,viewport.width+'px assessment editor');const heading=await page.getByRole('heading',{name:'Assessment builder',exact:true}).boundingBox();assert.ok(heading.y>=0&&heading.y<200,'Opening a builder starts at its heading, not the old list scroll position');if(viewport.width<768){const toggle=page.getByRole('button',{name:'Modules (4)',exact:true});assert.equal(await toggle.getAttribute('aria-expanded'),'false');await toggle.click();assert.equal(await toggle.getAttribute('aria-expanded'),'true');await page.locator('.module-select').nth(1).click();assert.equal(await toggle.getAttribute('aria-expanded'),'false');assert.equal(await page.getByLabel('Module title',{exact:true}).inputValue(),bank.modules[1].title);pass(viewport.width+'px collapsed module navigation selects the right module');}
 await c.close();
 }
}finally{await browser.close();}
console.log(checks+' mobile layout checks passed');
