// Interactive editor previews must run the actual candidate renderer and server flow.
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {chromium} from 'playwright';
import AxeBuilder from '@axe-core/playwright';
import {createClient} from '@supabase/supabase-js';
const base='http://127.0.0.1:5173';
const env=Object.fromEntries(readFileSync('.env.local','utf8').split('\n').filter(l=>l.includes('=')).map(l=>[l.slice(0,l.indexOf('=')),l.slice(l.indexOf('=')+1)]));
assert.match(env.NEXT_PUBLIC_SUPABASE_URL,/^http:\/\/(127\.0\.0\.1|localhost):\d+$/);
const db=createClient(env.NEXT_PUBLIC_SUPABASE_URL,env.SUPABASE_SERVICE_ROLE_KEY,{auth:{persistSession:false,autoRefreshToken:false}});
const browser=await chromium.launch({executablePath:'/usr/bin/chromium'}),admin=await browser.newContext(),guest=await browser.newContext(),other=await browser.newContext();
const created={assessments:[],attempts:[],preview_attempts:[]};let owner,checks=0;const pass=n=>{checks++;console.log('PASS:',n);};
async function api(context,path,body,status=200){const r=body?await context.request.post(base+path,{data:body,headers:{Origin:base}}):await context.request.get(base+path);const data=await r.json();assert.equal(r.status(),status,JSON.stringify(data));if(path==='/api/admin'&&status===200&&body){const table={save:'assessments',link:'attempts',preview:'preview_attempts','preview-unsaved':'preview_attempts'}[body.action];if(table)created[table].push(data.id);}return data;}
async function view(context,path){return api(context,'/api/candidate?token='+path.split('/').at(-1));}
async function command(context,path,action,answer={}){const state=await view(context,path);return api(context,'/api/candidate',{token:path.split('/').at(-1),action,answer,revision:state.revision});}
function content(s){return {title:s.title,description:s.description,seconds:s.seconds,sections:s.sections,config:s.config,currentIndex:s.currentIndex,module:s.module,answer:s.answer};}
const bank=JSON.parse(readFileSync('content/customer-service-core-v1.json','utf8'));
try{
 await api(admin,'/auth/login',{email:'recruiter@qa.invalid',password:'Local-QA-Only-57!Password'});await api(other,'/auth/login',{email:'second@qa.invalid',password:'Local-QA-Only-57!Password'});
 owner=(await db.auth.admin.listUsers()).data.users.find(u=>u.email==='recruiter@qa.invalid').id;
 const baseline=await api(admin,'/api/admin');
 for(const flexible of [true,false])for(const single of [true,false]){
  const assessment=structuredClone(bank);assessment.title='BROWSER SYNTHETIC Preview parity '+flexible+' '+single+' '+Date.now();assessment.modules=[assessment.modules[0]];assessment.modules[0].questions=assessment.modules[0].questions.slice(0,2);assessment.modules[0].sequential=false;assessment.config={...assessment.config,flexible,workSeconds:120,oneQuestionAtATime:single,allowBackNavigation:false};
  const saved=await api(admin,'/api/admin',{action:'save',assessment}),preview=await api(admin,'/api/admin',{action:'preview-unsaved',assessment:{...assessment,id:saved.id}}),link=await api(admin,'/api/admin',{action:'link',id:saved.id,alias:'BROWSER SYNTHETIC Preview parity'});
  assert.deepEqual(content(await view(admin,preview.path)),content(await view(guest,link.path)));
  const p=await command(admin,preview.path,'start'),c=await command(guest,link.path,'start');assert.deepEqual(content(p),content(c));assert.equal(p.module.questions.length,single?1:2);assert.ok(!JSON.stringify(p).includes('correctOptionId'));assert.ok(!JSON.stringify(p).includes('explanation'));
  if(single){const q=assessment.modules[0].questions[0],answer={choices:{[q.id]:q.correct}};assert.deepEqual(content(await command(admin,preview.path,'question-next',answer)),content(await command(guest,link.path,'question-next',answer)));assert.equal((await view(admin,preview.path)).module.questionIndex,1);}
  await api(guest,'/api/candidate?token='+preview.path.split('/').at(-1),undefined,404);await api(other,'/api/candidate?token='+preview.path.split('/').at(-1),undefined,404);
  pass((flexible?'shared':'section')+' timer '+(single?'individual':'all')+' questions: preview and candidate content/navigation match; signed-out and other owners excluded');
 }
 await api(admin,'/api/admin',{action:'preview-unsaved'},400);await api(guest,'/api/admin',{action:'preview-unsaved',assessment:bank},401);
 const standalone={...structuredClone(bank),modules:[bank.modules[0]],title:'BROWSER SYNTHETIC Unsaved preview '+Date.now()};const ephemeral=await api(admin,'/api/admin',{action:'preview-unsaved',assessment:standalone});assert.equal((await db.from('preview_attempts').select('assessment_id').eq('id',ephemeral.id).single()).data.assessment_id,null);const after=await api(admin,'/api/admin');assert.equal(after.library.length,baseline.library.length);assert.equal(after.assessments.length,baseline.assessments.length+4);assert.equal(after.attempts.length,baseline.attempts.length+4);pass('new unsaved previews need no saved assessment/module/candidate; invalid and unauthenticated requests rejected');
 const assessment=structuredClone(bank);assessment.title='BROWSER SYNTHETIC Editor preview '+Date.now();assessment.modules=[assessment.modules[0]];assessment.config.oneQuestionAtATime=true;assessment.config.allowBackNavigation=false;const saved=await api(admin,'/api/admin',{action:'save',assessment});
 for(const viewport of [{width:1440,height:1000},{width:390,height:844},{width:320,height:568}]){
  const page=await admin.newPage();await page.setViewportSize(viewport);await page.goto(base);await page.locator('.assessment-table tbody tr').filter({hasText:assessment.title}).getByRole('button',{name:'Edit assessment',exact:true}).click();const unsaved='Edited unsaved question '+viewport.width;await page.getByLabel('Question',{exact:true}).first().fill(unsaved);await page.getByRole('tab',{name:'Candidate preview',exact:true}).click();
  const response=page.waitForResponse(r=>r.url().endsWith('/api/admin')&&r.request().postDataJSON()?.action==='preview-unsaved');await page.getByRole('button',{name:'Preview assessment',exact:true}).click();const record=await(await response).json();created.preview_attempts.push(record.id);
  const dialog=page.getByRole('dialog',{name:'Candidate preview',exact:true}),frame=dialog;await frame.getByRole('checkbox').check();await frame.getByRole('button',{name:'Start assessment',exact:true}).click();await frame.getByRole('radiogroup',{name:unsaved,exact:true}).waitFor();assert.equal(await frame.locator('.candidate-question').count(),1);assert.equal(await frame.getByRole('button',{name:'Previous question',exact:true}).count(),0);
  await frame.getByRole('radio').first().check();await frame.getByRole('button',{name:'Next question',exact:true}).click();await frame.getByRole('radiogroup',{name:assessment.modules[0].questions[1].prompt,exact:true}).waitFor();assert.equal(await frame.locator('.candidate-question').count(),1);
  const promptBounds=await frame.locator('.candidate-question legend').boundingBox(),surfaceBounds=await page.locator('.candidate-preview-surface').boundingBox();assert.ok(promptBounds.y>=surfaceBounds.y-1&&promptBounds.y+promptBounds.height<=surfaceBounds.y+surfaceBounds.height+1,'Question prompt must remain visible after advancing');
  const audit=await new AxeBuilder({page}).withTags(['wcag2a','wcag2aa','wcag21aa']).analyze();assert.deepEqual(audit.violations.map(v=>({id:v.id,nodes:v.nodes.map(n=>n.failureSummary)})),[]);const bounds=await dialog.boundingBox();assert.ok(bounds.x>=-1&&bounds.y>=-1&&bounds.width<=viewport.width+1);assert.ok(await page.locator('.candidate-preview-surface').evaluate(n=>n.scrollWidth<=n.clientWidth+1));
  while(await frame.getByRole('button',{name:'Next question',exact:true}).count()){await frame.getByRole('radio').first().check();await frame.getByRole('button',{name:'Next question',exact:true}).click();}
  await frame.getByRole('radio').first().check();await frame.getByRole('button',{name:'Submit assessment',exact:true}).click();const confirmation=page.getByRole('alertdialog',{name:'Submit your assessment?',exact:true});await confirmation.getByRole('button',{name:'Cancel',exact:true}).click();await frame.getByRole('button',{name:'Submit assessment',exact:true}).click();await confirmation.getByRole('button',{name:'Confirm submission',exact:true}).click();await frame.getByRole('heading',{name:'Your responses have been submitted',exact:true}).waitFor();assert.equal(await frame.getByRole('link',{name:'Return to workspace',exact:true}).count(),0);assert.equal((await api(admin,'/api/admin')).attempts.length,baseline.attempts.length+4);
  await page.getByRole('button',{name:'Close preview',exact:true}).click();await page.getByRole('tab',{name:'Edit content',exact:true}).click();assert.equal(await page.getByLabel('Question',{exact:true}).first().inputValue(),unsaved);assert.equal((await api(admin,'/api/admin')).assessments.find(a=>a.id===saved.id).modules[0].questions[0].prompt,assessment.modules[0].questions[0].prompt);await page.close();pass(viewport.width+'px editor preview uses unsaved content, individual questions, forward-only progress, accessible layout and preserves edits without saving');
 }
 const page=await admin.newPage();await page.goto(base);if((await page.getByRole('heading',{name:'Assessments',exact:true}).count())===0)await page.getByRole('heading',{name:'Assessments',exact:true}).waitFor();await page.getByRole('button',{name:'Module library',exact:true}).click();await page.getByRole('button',{name:'Create module',exact:true}).click();await page.getByRole('dialog',{name:'Create a module',exact:true}).getByRole('button',{name:'Questions',exact:true}).click();await page.getByLabel('Module title',{exact:true}).fill('BROWSER SYNTHETIC Unsaved standalone module');await page.getByLabel('Question',{exact:true}).fill('Standalone question?');await page.getByLabel('Question 1, option 1',{exact:true}).fill('First');await page.getByLabel('Question 1, option 2',{exact:true}).fill('Second');await page.getByLabel('Answer explanation',{exact:true}).fill('First is correct.');await page.getByRole('tab',{name:'Candidate preview',exact:true}).click();const response=page.waitForResponse(r=>r.url().endsWith('/api/admin')&&r.request().postDataJSON()?.action==='preview-unsaved');await page.getByRole('button',{name:'Preview module',exact:true}).click();const record=await(await response).json();created.preview_attempts.push(record.id);const frame=page.getByRole('dialog',{name:'Candidate preview',exact:true});await frame.getByRole('checkbox').check();await frame.getByRole('button',{name:'Start assessment',exact:true}).click();await frame.getByRole('radiogroup',{name:'Standalone question?',exact:true}).waitFor();assert.equal((await api(admin,'/api/admin')).library.length,baseline.library.length);await page.close();pass('blank custom module can be interactively previewed before saving to the library');
 const typingPage=await admin.newPage();await typingPage.goto(base);await typingPage.getByRole('button',{name:'Module library',exact:true}).click();await typingPage.getByRole('button',{name:'Create module',exact:true}).click();await typingPage.getByRole('dialog',{name:'Create a module',exact:true}).getByRole('button',{name:'Typing',exact:true}).click();await typingPage.getByLabel('Module title',{exact:true}).fill('BROWSER SYNTHETIC Unsaved typing preview');await typingPage.getByLabel('Typing passage',{exact:true}).fill(bank.modules[1].passage);await typingPage.getByLabel('Typing duration (seconds)',{exact:true}).fill('15');await typingPage.getByRole('tab',{name:'Candidate preview',exact:true}).click();const typingResponse=typingPage.waitForResponse(r=>r.url().endsWith('/api/admin')&&r.request().postDataJSON()?.action==='preview-unsaved');await typingPage.getByRole('button',{name:'Preview module',exact:true}).click();const typingRecord=await(await typingResponse).json();created.preview_attempts.push(typingRecord.id);const typingDialog=typingPage.getByRole('dialog',{name:'Candidate preview',exact:true});await typingDialog.getByRole('checkbox').check();await typingDialog.getByRole('button',{name:'Start assessment',exact:true}).click();await typingDialog.getByRole('button',{name:'Start 15-second task',exact:true}).waitFor();const typingState=await view(admin,typingRecord.path);assert.equal(typingState.config.flexible,true);assert.equal(typingState.answer.typing,undefined);await typingDialog.getByRole('button',{name:'Start 15-second task',exact:true}).click();await typingDialog.getByLabel('Your typed copy',{exact:true}).waitFor();assert.ok((await view(admin,typingRecord.path)).answer.typing);assert.equal((await api(admin,'/api/admin')).library.length,baseline.library.length);await typingPage.close();pass('standalone typing preview keeps shared timer style and deliberate measured start instead of silently switching the candidate experience');

}finally{await browser.close();for(const table of ['attempts','preview_attempts','assessments'])if(created[table].length&&owner){const {error}=await db.from(table).delete().eq('owner',owner).in('id',created[table]);if(error)throw error;}}
console.log(checks+' preview parity checks passed');
