// Real question progression, authorization, persistence and scoring. Loopback only.
import {chromium} from 'playwright';
import AxeBuilder from '@axe-core/playwright';
import assert from 'node:assert/strict';
import {readFileSync,mkdirSync} from 'node:fs';
import {createClient} from '@supabase/supabase-js';
const base='http://127.0.0.1:5173';
const bank=JSON.parse(readFileSync('content/customer-service-core-v1.json','utf8'));
const env=Object.fromEntries(readFileSync('.env.local','utf8').split('\n').filter(l=>l.includes('=')).map(l=>[l.slice(0,l.indexOf('=')),l.slice(l.indexOf('=')+1)]));
assert.match(env.NEXT_PUBLIC_SUPABASE_URL,/^http:\/\/(127\.0\.0\.1|localhost):\d+$/);
const db=createClient(env.NEXT_PUBLIC_SUPABASE_URL,env.SUPABASE_SERVICE_ROLE_KEY,{auth:{persistSession:false,autoRefreshToken:false}});
const created={assessments:[],attempts:[],preview_attempts:[]};let owner;
const browser=await chromium.launch({executablePath:process.env.CHROMIUM_PATH||'/usr/bin/chromium'});
let checks=0;const pass=name=>{checks++;console.log('PASS:',name);};
mkdirSync('test-results/question-flow',{recursive:true});
async function adminApi(page,body){const r=await page.evaluate(async body=>{const r=await fetch('/api/admin',{method:body?'POST':'GET',headers:{'Content-Type':'application/json'},...(body?{body:JSON.stringify(body)}:{})});return {status:r.status,data:await r.json()};},body);assert.equal(r.status,200,JSON.stringify(r.data));const table={save:'assessments',link:'attempts',preview:'preview_attempts'}[body?.action];if(table&&r.data.id&&!created[table].includes(r.data.id))created[table].push(r.data.id);return r.data;}
async function view(page,token){return page.evaluate(async token=>(await fetch('/api/candidate?token='+token)).json(),token);}
async function command(page,token,action,answer={},index){return page.evaluate(async ({token,action,answer,index})=>{for(let tries=0;tries<3;tries++){const state=await(await fetch('/api/candidate?token='+token)).json();const r=await fetch('/api/candidate',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({token,action,answer,index,revision:state.revision})});const data=await r.json();if(r.status!==409)return {status:r.status,data};}throw new Error('Concurrent save did not settle');},{token,action,answer,index});}
async function audit(page,name){await page.evaluate(async()=>{await Promise.all(document.getAnimations().filter(a=>a.playState==='running'&&Number.isFinite(a.effect?.getComputedTiming().endTime)).map(a=>a.finished.catch(()=>{})));});const r=await new AxeBuilder({page}).withTags(['wcag2a','wcag2aa','wcag21aa']).analyze();assert.deepEqual(r.violations.map(v=>({id:v.id,nodes:v.nodes.map(n=>n.failureSummary)})),[]);assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));pass(name);}
async function confirmationLayout(page,device,viewport) {
 const dialog=page.getByRole('alertdialog',{name:'Submit your assessment?',exact:true});await dialog.waitFor();
 for(const [size,dimensions] of [['desktop',{width:1440,height:1000}],['mobile',{width:390,height:844}],['compact',{width:320,height:568}]]) {
  await page.setViewportSize(dimensions);await audit(page,device+' '+size+' submission dialog accessibility and reflow');
  const bounds=await dialog.evaluate(node=>{const rect=n=>{const r=n.getBoundingClientRect();return {left:r.left,top:r.top,right:r.right,bottom:r.bottom,width:r.width,height:r.height};};return {panel:rect(node),title:rect(node.querySelector('[data-slot="alert-dialog-title"]')),message:rect(node.querySelector('[data-slot="alert-dialog-description"]')),buttons:[...node.querySelectorAll('button')].map(rect)};});
  assert.ok(bounds.panel.left>=8&&bounds.panel.right<=dimensions.width-8&&bounds.panel.top>=8&&bounds.panel.bottom<=dimensions.height-8,'Confirmation must fit within the screen');
  assert.ok(bounds.title.width>=200&&bounds.message.width>=200,'Confirmation text must have room to wrap in full words');assert.ok(bounds.title.height<100&&bounds.message.height<150,'Confirmation text must not stack vertically');
  for(const button of bounds.buttons)assert.ok(button.left>=bounds.panel.left&&button.right<=bounds.panel.right&&button.top>=bounds.panel.top&&button.bottom<=bounds.panel.bottom);
  await page.screenshot({path:'test-results/question-flow/'+device+'-confirmation-'+size+'.png',fullPage:false});
 }
 await page.setViewportSize(viewport);
}
async function choose(page,module,n){const q=module.questions[n];await page.getByRole('radiogroup',{name:q.prompt,exact:true}).getByRole('radio').nth(q.correct).check();}
try {
 const adminContext=await browser.newContext(),admin=await adminContext.newPage();await admin.goto(base+'/login');await admin.getByLabel('Email address',{exact:true}).fill('recruiter@qa.invalid');await admin.getByLabel('Password',{exact:true}).fill('Local-QA-Only-57!Password');await admin.getByRole('button',{name:'Sign in',exact:true}).click();await admin.getByRole('heading',{name:'Assessments',exact:true}).waitFor();owner=(await db.auth.admin.listUsers()).data.users.find(u=>u.email==='recruiter@qa.invalid').id;
 for(const [device,shared,viewport] of [['desktop',true,{width:1440,height:1000}],['mobile',false,{width:390,height:844}]]){
  const assessment=structuredClone(bank);assessment.title='BROWSER SYNTHETIC Question flow '+device+' '+Date.now();assessment.config.flexible=shared;assessment.config.workSeconds=300;assert.equal(assessment.config.oneQuestionAtATime,true);assert.equal(assessment.config.allowBackNavigation,false);
  const saved=await adminApi(admin,{action:'save',assessment});await admin.reload();await admin.locator('.assessment-card').filter({has:admin.getByRole('heading',{name:assessment.title,exact:true})}).getByRole('button',{name:'Edit assessment',exact:true}).click();await admin.getByText('Candidate settings',{exact:true}).click();assert.ok(await admin.getByLabel('Show one question at a time',{exact:true}).isChecked());assert.ok(!await admin.getByLabel('Allow going back to earlier answers',{exact:true}).isChecked());await admin.getByRole('button',{name:'Back to assessments',exact:true}).click();pass(device+' persisted display and navigation settings are editable');
  const link=await adminApi(admin,{action:'link',id:saved.id,alias:'BROWSER SYNTHETIC Forward candidate '+device}),token=link.path.split('/').at(-1);const context=await browser.newContext({viewport}),page=await context.newPage();await page.goto(base+link.path);await page.getByRole('checkbox').check();await page.getByRole('button',{name:'Start assessment',exact:true}).click();await page.locator('.candidate-question').waitFor();assert.equal(await page.locator('.candidate-question').count(),1);
  const original=await view(page,token),first=assessment.modules[0];assert.equal(original.module.questions.length,1);assert.ok(!JSON.stringify(original).includes(first.questions[1].prompt));assert.equal(await page.getByRole('button',{name:'Previous question',exact:true}).count(),0);if(shared)assert.ok(await page.locator('.test-outline button').evaluateAll(nodes=>nodes.every(n=>n.disabled)));pass(device+' signed-out candidate sees only the current question and no backward controls');
  if(shared){assert.equal((await command(page,token,'navigate',{},3)).status,400);assert.equal((await command(page,token,'navigate',{},1)).status,400);assert.equal((await command(page,token,'submit')).status,400);}assert.equal((await command(page,token,'question-back')).status,400);assert.equal((await command(page,token,'save',{choices:{[first.questions[1].id]:first.questions[1].correct}})).status,400);pass(device+' server rejects backward, future-question and premature section access');
  await choose(page,first,0);
  // Losing an advancement response must resume at the committed next question.
  if(device==='mobile'){let firstFailure=true;await page.route('**/api/candidate',async route=>{if(firstFailure&&route.request().postDataJSON()?.action==='question-next'){firstFailure=false;await route.fetch();await route.abort('failed');}else await route.continue();});await page.getByRole('button',{name:'Next question',exact:true}).click();await page.getByRole('alert').filter({hasText:'Saving needs attention'}).waitFor();await page.getByRole('button',{name:'Reload saved state',exact:true}).click();}
  else await page.getByRole('button',{name:'Next question',exact:true}).click();
  await page.getByRole('radiogroup',{name:first.questions[1].prompt,exact:true}).waitFor();assert.equal(await page.locator('.candidate-question').count(),1);assert.equal(await page.getByRole('radiogroup',{name:first.questions[0].prompt,exact:true}).count(),0);const progressed=await view(page,token);assert.equal(progressed.answer.questionIndex,1);assert.equal(progressed.deadline,original.deadline);assert.ok(!JSON.stringify(progressed).includes(first.questions[0].prompt));assert.equal((await command(page,token,'save',{choices:{[first.questions[0].id]:(first.questions[0].correct+1)%first.questions[0].options.length}})).status,400);assert.equal((await command(page,token,'question-back')).status,400);pass(device+' advancement locks the earlier answer and survives a lost acknowledgement');
  await page.reload();await page.getByRole('radiogroup',{name:first.questions[1].prompt,exact:true}).waitFor();assert.equal((await view(page,token)).deadline,original.deadline);await audit(page,device+' one-question accessibility and refresh');await page.screenshot({path:'test-results/question-flow/'+device+'.png',fullPage:true});await choose(page,first,1);await page.getByRole('button',{name:'Save & continue',exact:true}).click();await page.getByLabel('Your typed copy',{exact:true}).waitFor({state:shared?'hidden':'visible'});
  if(shared){await page.getByRole('button',{name:'Start 60-second task',exact:true}).click();await page.getByLabel('Your typed copy',{exact:true}).waitFor();}
  await page.getByLabel('Your typed copy',{exact:true}).fill(assessment.modules[1].passage);if(shared)await page.getByRole('button',{name:'Finish complete passage early',exact:true}).click();await page.getByRole('button',{name:'Save & continue',exact:true}).click();const policy=assessment.modules[2];await page.getByRole('radiogroup',{name:policy.questions[0].prompt,exact:true}).waitFor();if(shared)assert.equal((await command(page,token,'navigate',{},0)).status,400);await choose(page,policy,0);await page.getByRole('button',{name:'Next question',exact:true}).click();await page.getByRole('radiogroup',{name:policy.questions[1].prompt,exact:true}).waitFor();await choose(page,policy,1);await page.getByRole('button',{name:'Save & continue',exact:true}).click();await page.getByLabel('Your reply to the customer',{exact:true}).fill(assessment.modules[3].example);assert.equal(await page.getByRole('button',{name:'Review answers',exact:true}).count(),0);await page.getByRole('button',{name:'Submit assessment',exact:true}).click();await confirmationLayout(page,device,viewport);
  if(shared){
   const dialog=page.getByRole('alertdialog');await dialog.getByRole('button',{name:'Cancel',exact:true}).click();await dialog.waitFor({state:'hidden'});assert.equal((await view(page,token)).status,'in-progress');assert.equal(await page.getByLabel('Your reply to the customer',{exact:true}).inputValue(),assessment.modules[3].example);assert.ok(await page.getByRole('button',{name:'Submit assessment',exact:true}).evaluate(n=>n===document.activeElement));
   await page.getByRole('button',{name:'Submit assessment',exact:true}).click();await dialog.waitFor();await page.keyboard.press('Escape');await dialog.waitFor({state:'hidden'});pass('cancel and Escape preserve the writing and restore focus without submitting');
   let release,started;const gate=new Promise(r=>{release=r;}),pending=new Promise(r=>{started=r;});let submits=0;
   const failure=async route=>{if(route.request().method()==='POST'&&route.request().postDataJSON()?.action==='submit'){submits++;started();await gate;await route.fulfill({status:503,contentType:'application/json',body:JSON.stringify({error:'Unable to confirm submission. Your answers are still here. Please try again.'})});}else await route.continue();};
   await page.route('**/api/candidate',failure);await page.getByRole('button',{name:'Submit assessment',exact:true}).click();await dialog.getByRole('button',{name:'Confirm submission',exact:true}).click();await pending;assert.ok(await dialog.getByRole('button',{name:'Confirm submission',exact:true}).isDisabled());assert.ok(await dialog.getByRole('button',{name:'Cancel',exact:true}).isDisabled());await dialog.getByRole('button',{name:'Confirm submission',exact:true}).evaluate(n=>{n.click();n.click();});await page.keyboard.press('Escape');assert.ok(await dialog.isVisible());release();await dialog.getByRole('alert').waitFor();assert.equal(submits,1);await page.unroute('**/api/candidate',failure);assert.equal((await view(page,token)).status,'in-progress');await confirmationLayout(page,'failed',viewport);assert.equal(await page.getByLabel('Your reply to the customer',{exact:true}).inputValue(),assessment.modules[3].example);pass('slow failed submission stays visible, prevents duplicate requests and retains all writing');
   await dialog.getByRole('button',{name:'Confirm submission',exact:true}).click();
  }else await page.getByRole('alertdialog').getByRole('button',{name:'Submit assessment',exact:true}).click();await page.getByRole('heading',{name:shared?'Your responses have been submitted':/You’re all done/}).waitFor();if(shared)await page.locator('.completion-card h1:focus').waitFor();
  const record=(await adminApi(admin)).attempts.find(a=>a.id===link.id);assert.equal(record.result.objectiveCorrect,4);assert.equal(record.result.objectiveTotal,4);for(const m of [first,policy])assert.equal(Object.keys(record.answers[m.id].choices).length,2);assert.equal(record.answers[assessment.modules[3].id].text,assessment.modules[3].example);assert.equal((await command(page,token,'submit',{text:'duplicate replacement'})).status,200);assert.deepEqual((await adminApi(admin)).attempts.find(a=>a.id===link.id).answers,record.answers);pass(device+' full forward-only typing/writing journey saves all choices and immutable results');
  const writing=assessment.modules[3],ratings=Object.fromEntries(writing.rubric.map(r=>[writing.id+':'+r.id,3])),evidence=Object.fromEntries(Object.keys(ratings).map(k=>[k,'Quote: '+writing.example.slice(0,100)]));await adminApi(admin,{action:'review',id:record.id,revision:record.revision,review:{ratings,evidence,notes:'All evidence is preserved in the forward-only attempt.',outcome:'reviewed'}});assert.equal(Object.keys((await adminApi(admin)).attempts.find(a=>a.id===link.id).review.ratings).length,5);pass(device+' human review retains all original evidence');await context.close();
 }
 // Assessors can explicitly choose a reviewable single-question assessment instead.
 const alternative=structuredClone(bank);alternative.title='BROWSER SYNTHETIC Reviewable single questions '+Date.now();alternative.modules=[alternative.modules[0]];alternative.config.allowBackNavigation=true;alternative.config.workSeconds=120;const saved=await adminApi(admin,{action:'save',assessment:alternative}),link=await adminApi(admin,{action:'link',id:saved.id,alias:'BROWSER SYNTHETIC Allowed back'});const context=await browser.newContext(),page=await context.newPage();await page.goto(base+link.path);await page.getByRole('checkbox').check();await page.getByRole('button',{name:'Start assessment',exact:true}).click();await page.locator('.candidate-question').waitFor();await choose(page,alternative.modules[0],0);await page.getByRole('button',{name:'Next question',exact:true}).click();await page.getByRole('radiogroup',{name:alternative.modules[0].questions[1].prompt,exact:true}).waitFor();await choose(page,alternative.modules[0],1);await page.getByRole('button',{name:'Previous question',exact:true}).click();await page.getByRole('radiogroup',{name:alternative.modules[0].questions[0].prompt,exact:true}).waitFor();assert.ok(await page.getByRole('radiogroup').getByRole('radio').nth(alternative.modules[0].questions[0].correct).isChecked());await page.getByRole('radiogroup').getByRole('radio').nth((alternative.modules[0].questions[0].correct+1)%alternative.modules[0].questions[0].options.length).check();await page.getByRole('button',{name:'Next question',exact:true}).click();await page.getByRole('radiogroup',{name:alternative.modules[0].questions[1].prompt,exact:true}).waitFor();assert.ok(await page.getByRole('radiogroup').getByRole('radio').nth(alternative.modules[0].questions[1].correct).isChecked());pass('explicitly enabled backward navigation preserves and edits prior choices');await page.getByRole('button',{name:'Review answers',exact:true}).click();await page.getByRole('heading',{name:'Review your answers',exact:true}).waitFor();await page.getByRole('button',{name:'Submit assessment',exact:true}).click();const dialog=page.getByRole('alertdialog');await dialog.getByRole('button',{name:'Cancel',exact:true}).click();await page.getByRole('heading',{name:'Review your answers',exact:true}).waitFor();assert.equal((await view(page,link.path.split('/').at(-1))).status,'in-progress');await page.getByRole('button',{name:'Submit assessment',exact:true}).click();await dialog.getByRole('button',{name:'Confirm submission',exact:true}).click();await page.getByRole('heading',{name:'Your responses have been submitted',exact:true}).waitFor();pass('reviewable assessment also cancels and submits through the confirmation dialog');await context.close();
}finally{await browser.close();for(const table of ['attempts','preview_attempts','assessments'])if(created[table].length){assert.ok(owner);const {error}=await db.from(table).delete().eq('owner',owner).in('id',created[table]);if(error)throw error;}}
console.log(checks+' question-flow checks passed');
