// Real request persistence, clipboard images, storage and tenant boundaries.
// This suite is deliberately restricted to generated loopback QA configuration.
import assert from 'node:assert/strict';
import {readFileSync, mkdirSync} from 'node:fs';
import {chromium} from 'playwright';
import AxeBuilder from '@axe-core/playwright';
import {createClient} from '@supabase/supabase-js';
import sharp from 'sharp';

const base='http://127.0.0.1:5173', bucket='workspace-request-images';
const text=readFileSync('.env.local','utf8');assert.ok(text.startsWith('# Generated local QA configuration'));
const values=Object.fromEntries(text.split('\n').filter(l=>l.includes('=')).map(l=>[l.slice(0,l.indexOf('=')),l.slice(l.indexOf('=')+1)]));
assert.match(values.NEXT_PUBLIC_SUPABASE_URL,/^http:\/\/(127\.0\.0\.1|localhost):\d+$/);
const service=createClient(values.NEXT_PUBLIC_SUPABASE_URL,values.SUPABASE_SERVICE_ROLE_KEY,{auth:{persistSession:false,autoRefreshToken:false}});
const browser=await chromium.launch({executablePath:process.env.CHROMIUM_PATH||'/usr/bin/chromium'});
const created={cards:[],users:[]};let tenantId,original,ownerContext,hadBoard=false;let checks=0;
const pass=name=>{checks++;console.log('PASS:',name);};mkdirSync('test-results/requests',{recursive:true});
const png=await sharp({create:{width:800,height:450,channels:3,background:'#dfeee8'}}).png().toBuffer();
async function session(email='recruiter@qa.invalid',viewport={width:1440,height:1000}){const c=await browser.newContext({baseURL:base,viewport,permissions:['clipboard-read','clipboard-write']});const r=await c.request.post('/auth/login',{data:{email,password:'Local-QA-Only-57!Password'}});assert.equal(r.status(),200);return c;}
async function board(context){const r=await context.request.get('/api/requests');assert.equal(r.status(),200);return r.json();}
async function post(context,data,status=200){const r=await context.request.post('/api/requests',{data});assert.equal(r.status(),status,JSON.stringify(await r.json()));return r.json();}
async function audit(page,name){await page.evaluate(async()=>{await Promise.all(document.getAnimations().filter(a=>a.playState==='running'&&Number.isFinite(a.effect?.getComputedTiming().endTime)).map(a=>a.finished.catch(()=>{})));});const result=await new AxeBuilder({page}).withTags(['wcag2a','wcag2aa','wcag21aa']).analyze();assert.deepEqual(result.violations.map(v=>({id:v.id,nodes:v.nodes.map(n=>n.failureSummary)})),[]);assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));pass(name);}
async function requestsPage(context){const page=await context.newPage();await page.goto('/');await page.getByRole('button',{name:'Requests',exact:true}).click();await page.getByRole('heading',{name:'Requests',exact:true}).waitFor();await page.getByRole('button',{name:'New request',exact:true}).waitFor();return page;}
const fields=(id,columnId,assigneeId=null)=>({action:'save',id,revision:0,title:'REQUESTS SYNTHETIC '+id,description:'Saved request details',columnId,assigneeId,priority:'normal'});
try {
 const unsigned=await browser.newContext({baseURL:base});assert.equal((await unsigned.request.get('/api/requests')).status(),401);assert.equal((await unsigned.request.post('/api/requests',{data:{}})).status(),401);assert.equal((await unsigned.request.post('/api/requests/images',{data:{}})).status(),401);pass('Signed-out visitors cannot read, create or upload requests');
 ownerContext=await session();const admin=await ownerContext.request.get('/api/admin');assert.equal(admin.status(),200);const details=await admin.json();tenantId=(await service.from('workspace_members').select('tenant_id').eq('id',details.userId).single()).data.tenant_id;assert.ok(tenantId);original=await board(ownerContext);hadBoard=!!original.revision;
 const second=await session('second@qa.invalid');assert.notEqual((await service.from('workspace_members').select('tenant_id').eq('id',(await(await second.request.get('/api/admin')).json()).userId).single()).data.tenant_id,tenantId);
 const stamp=Date.now(),editorEmail=`requests-editor-${stamp}@qa.invalid`,viewerEmail=`requests-viewer-${stamp}@qa.invalid`;
 for(const [email,role,name] of [[editorEmail,'editor','QA request editor'],[viewerEmail,'viewer','QA request viewer']]){
  const added=await service.auth.admin.createUser({email,password:'Local-QA-Only-57!Password',email_confirm:true});assert.ifError(added.error);created.users.push(added.data.user.id);
  const r=await ownerContext.request.post('/api/accounts',{data:{action:'add',email,name,role}});assert.equal(r.status(),200);
 }
 const editorId=created.users[0],page=await requestsPage(ownerContext),errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('request',r=>{if(r.method()==='POST'&&new URL(r.url()).pathname==='/api/requests'){const data=r.postDataJSON();if(data.action==='save'&&data.revision===0&&!created.cards.includes(data.id))created.cards.push(data.id);}});
 await audit(page,'Empty Requests board is accessible and fits desktop');assert.equal((await board(second)).requests.length,0);pass('Separate business sees its own empty board');
 await page.getByRole('button',{name:'Edit columns',exact:true}).click();await page.getByLabel('Column 1 name',{exact:true}).fill('Inbox');await page.getByRole('button',{name:'Add column',exact:true}).click();await page.getByLabel('Column 4 name',{exact:true}).fill('Review');await page.getByRole('button',{name:'Move column 4 left',exact:true}).click();await page.getByRole('button',{name:'Save columns',exact:true}).click();await page.getByRole('dialog').waitFor({state:'hidden'});const configured=await board(ownerContext);assert.deepEqual(configured.columns.map(c=>c.name),['Inbox','In progress','Review','Done']);pass('Column names, new columns and ordering persist');
 const title='REQUESTS SYNTHETIC Screenshot '+stamp;await page.getByRole('button',{name:'New request',exact:true}).click();await page.getByLabel('Request title',{exact:true}).fill(title);await page.getByLabel('Assign request to',{exact:true}).selectOption(editorId);await page.getByLabel('Request priority',{exact:true}).selectOption('high');
 await page.evaluate(async()=>navigator.clipboard.writeText('A pasted request description.'));await page.getByLabel('Request description',{exact:true}).focus();await page.keyboard.press('Control+V');assert.equal(await page.getByLabel('Request description',{exact:true}).inputValue(),'A pasted request description.');
 await page.evaluate(async bytes=>{const blob=new Blob([Uint8Array.from(bytes)],{type:'image/png'});await navigator.clipboard.write([new ClipboardItem({'image/png':blob})]);},Array.from(png));await page.keyboard.press('Control+V');await page.locator('.request-images figure').waitFor();assert.equal(await page.locator('.request-images figure').count(),1);assert.equal(await page.getByLabel('Request description',{exact:true}).inputValue(),'A pasted request description.');pass('Native clipboard image paste adds a screenshot without replacing text');
 await page.getByLabel('Upload request images',{exact:true}).setInputFiles({name:'Supporting screenshot.png',mimeType:'image/png',buffer:png});assert.equal(await page.locator('.request-images figure').count(),2);await audit(page,'Request editor with pasted and uploaded images is accessible');
 const failedSave=async route=>{if(route.request().method()==='POST')await route.fulfill({status:503,contentType:'application/json',body:JSON.stringify({error:'Temporary saving failure. Please retry.'})});else await route.continue();};await page.route('**/api/requests',failedSave);await page.getByRole('button',{name:'Save request',exact:true}).click();await page.getByRole('alert').filter({hasText:'Temporary saving failure'}).waitFor();assert.equal(await page.getByLabel('Request title',{exact:true}).inputValue(),title);assert.equal(await page.locator('.request-images figure').count(),2);await page.unroute('**/api/requests',failedSave);pass('Failed card save preserves the draft and both pending screenshots');
 let lost=false;const lostUpload=async route=>{if(!lost&&route.request().method()==='POST'){lost=true;await route.fetch();await route.abort('failed');}else await route.continue();};await page.route('**/api/requests/images',lostUpload);await page.getByRole('button',{name:'Save request',exact:true}).click();await page.getByRole('alert').filter({hasText:/fetch/i}).waitFor();assert.equal(await page.locator('.request-images figure').count(),2);await page.unroute('**/api/requests/images',lostUpload);await page.getByRole('button',{name:'Save request',exact:true}).click();await page.getByRole('dialog').waitFor({state:'hidden'});pass('Lost committed image response retries without duplicate cards or images');
 let saved=(await board(ownerContext)).requests.find(c=>c.title===title);assert.ok(saved);if(!created.cards.includes(saved.id))created.cards.push(saved.id);assert.equal(saved.assigneeId,editorId);assert.equal(saved.priority,'high');assert.equal(saved.images.length,2);assert.equal((await board(ownerContext)).requests.filter(c=>c.title===title).length,1);assert.equal(saved.description,'A pasted request description.');pass('Assigned request, description, priority and both images save together');
 for(const image of saved.images){const r=await ownerContext.request.get(image.url);assert.equal(r.status(),200);assert.equal(r.headers()['content-type'],'image/webp');assert.match(r.headers()['cache-control'],/private.*no-store/);assert.equal((await sharp(await r.body()).metadata()).format,'webp');assert.equal((await unsigned.request.get(image.url)).status(),401);assert.equal((await second.request.get(image.url)).status(),404);}const raw=(await service.from('request_images').select('object_path').eq('request_id',saved.id)).data[0];assert.equal((await unsigned.request.get(values.NEXT_PUBLIC_SUPABASE_URL+'/storage/v1/object/public/'+bucket+'/'+raw.object_path)).status(),400);pass('Images are valid private files protected from visitors and other businesses');
 await page.reload();await page.getByRole('button',{name:'Requests',exact:true}).click();await page.getByRole('button',{name:'Open request: '+title,exact:true}).waitFor();pass('Board survives refresh with saved images and assignment');
 for(const [name,viewport]of[['desktop',{width:1440,height:1000}],['mobile',{width:390,height:844}],['compact',{width:320,height:568}]]){
  await page.setViewportSize(viewport);await audit(page,name+' populated board accessibility and reflow');await page.screenshot({path:'test-results/requests/'+name+'-board.png',fullPage:true});await page.getByRole('button',{name:'Open request: '+title,exact:true}).click();await audit(page,name+' image editor accessibility and reflow');await page.screenshot({path:'test-results/requests/'+name+'-editor.png',fullPage:true});await page.getByRole('button',{name:'Cancel',exact:true}).click();await page.getByRole('dialog').waitFor({state:'hidden'});
 }
 await page.setViewportSize({width:1440,height:1000});await page.getByLabel('Filter by assignee',{exact:true}).selectOption('me');assert.equal(await page.locator('.request-card').count(),0);await page.getByLabel('Filter by assignee',{exact:true}).selectOption(editorId);assert.equal(await page.locator('.request-card').count(),1);await page.getByLabel('Search requests',{exact:true}).fill('does not match');assert.equal(await page.locator('.request-card').count(),0);await page.getByLabel('Search requests',{exact:true}).fill('');await page.getByLabel('Filter by assignee',{exact:true}).selectOption('all');pass('Search and assignment filters reflect the visible requests');
 await page.getByRole('button',{name:'Open request: '+title,exact:true}).click();await page.getByLabel('Request column',{exact:true}).selectOption('in-progress');await page.getByRole('button',{name:'Save request',exact:true}).click();await page.getByRole('dialog').waitFor({state:'hidden'});assert.equal((await board(ownerContext)).requests.find(c=>c.id===saved.id).columnId,'in-progress');pass('Column picker moves requests without drag, including touch and keyboard users');
 const secondId=crypto.randomUUID();created.cards.push(secondId);await post(ownerContext,fields(secondId,'done'));await page.getByRole('button',{name:'Refresh requests',exact:true}).click();await page.getByRole('button',{name:'Open request: REQUESTS SYNTHETIC '+secondId,exact:true}).waitFor();await page.locator('.request-card').filter({has:page.getByRole('button',{name:'Open request: '+title,exact:true})}).dragTo(page.getByRole('region',{name:'Done',exact:true}));
 await page.waitForFunction(id=>document.querySelector('[aria-label="Done"]')?.querySelector(`[aria-label="Open request: ${id}"]`),title);assert.equal((await board(ownerContext)).requests.find(c=>c.id===saved.id).columnId,'done');pass('Dragging a card changes its saved column');const moved=(await board(ownerContext)).requests.find(c=>c.id===saved.id);await post(ownerContext,{action:'move',id:saved.id,revision:moved.revision,columnId:'done',beforeId:secondId});assert.deepEqual((await board(ownerContext)).requests.filter(c=>c.columnId==='done').map(c=>c.id),[saved.id,secondId]);pass('Request ordering within a column persists');
 const editor=await session(editorEmail),viewer=await session(viewerEmail);assert.ok((await board(editor)).users.some(u=>u.id===editorId));assert.ok((await board(editor)).requests.some(c=>c.id===saved.id));const revision=(await board(editor)).requests.find(c=>c.id===saved.id).revision;await post(editor,{action:'move',id:saved.id,revision,columnId:'new'});await post(ownerContext,{action:'move',id:saved.id,revision,columnId:'done'},409);pass('Editors share the board and stale updates cannot overwrite another user');
 await post(second,{action:'move',id:saved.id,revision:revision+1,columnId:'done'},404);await post(viewer,{action:'move',id:saved.id,revision:revision+1,columnId:'done'},403);assert.equal((await viewer.request.delete(saved.images[0].url)).status(),403);assert.equal((await viewer.request.post('/api/requests/images',{data:{}})).status(),403);assert.equal((await viewer.request.get(saved.images[0].url)).status(),200);pass('Viewers can read images but cannot change, upload or delete requests');const viewerPage=await viewer.newPage();await viewerPage.goto('/');await viewerPage.getByRole('button',{name:'Requests',exact:true}).click();await viewerPage.getByRole('button',{name:'Open request: '+title,exact:true}).waitFor();assert.equal(await viewerPage.getByRole('button',{name:'New request',exact:true}).count(),0);assert.equal(await viewerPage.getByRole('button',{name:'Edit columns',exact:true}).count(),0);await viewerPage.getByRole('button',{name:'Open request: '+title,exact:true}).click();assert.ok(await viewerPage.getByLabel('Request title',{exact:true}).evaluate(n=>n.readOnly));assert.equal(await viewerPage.getByRole('button',{name:'Save request',exact:true}).count(),0);await audit(viewerPage,'Viewer request details are accessible and read-only');await viewerPage.close();
 await post(ownerContext,fields(crypto.randomUUID(),'new',(await(await second.request.get('/api/admin')).json()).userId),400);
 const membership=(await service.from('workspace_members').select('revision').eq('id',editorId).single()).data;assert.equal((await ownerContext.request.post('/api/accounts',{data:{action:'update',id:editorId,role:'editor',status:'suspended',revision:membership.revision}})).status(),200);await post(ownerContext,fields(crypto.randomUUID(),'new',editorId),400);assert.equal((await editor.request.get('/api/requests')).status(),401);assert.equal((await editor.request.get(saved.images[0].url)).status(),401);pass('Foreign or inactive assignees are rejected and suspension blocks an existing session');
 const mismatch=await ownerContext.request.post('/api/requests',{headers:{'X-Assess-Tenant':crypto.randomUUID()},data:fields(crypto.randomUUID(),'new')});assert.equal(mismatch.status(),409);pass('A business switched in another tab cannot receive a stale card save');
 const forged=await ownerContext.request.post('/api/requests',{headers:{Origin:'https://foreign.invalid'},data:{action:'archive',id:saved.id,revision:revision+1}});assert.equal(forged.status(),403);assert.equal((await ownerContext.request.delete(saved.images[0].url,{headers:{Origin:'https://foreign.invalid'}})).status(),403);assert.equal((await ownerContext.request.post('/api/requests/images',{headers:{Origin:'https://foreign.invalid'},data:{}})).status(),403);pass('Cross-origin request and image mutations are blocked');
 const publicClient=createClient(values.NEXT_PUBLIC_SUPABASE_URL,values.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY);for(const table of ['request_boards','workspace_requests','request_images'])assert.ok((await publicClient.from(table).select('*')).error);const login=await publicClient.auth.signInWithPassword({email:'second@qa.invalid',password:'Local-QA-Only-57!Password'});assert.ifError(login.error);assert.deepEqual((await publicClient.from('workspace_requests').select('*').eq('id',saved.id)).data,[]);assert.deepEqual((await publicClient.from('request_images').select('*').eq('request_id',saved.id)).data,[]);assert.equal((await publicClient.storage.from(bucket).download(raw.object_path)).data,null);pass('Database RLS and private storage also deny direct cross-business access');
 const upload=async(file,id=crypto.randomUUID())=>ownerContext.request.post('/api/requests/images',{multipart:{requestId:saved.id,id,file}});
 assert.equal((await upload({name:'fake.png',mimeType:'image/png',buffer:Buffer.from('<svg xmlns="http://www.w3.org/2000/svg"><script>alert(1)</script></svg>')})).status(),400);assert.equal((await upload({name:'too-large.png',mimeType:'image/png',buffer:Buffer.alloc(3*1024*1024+1)})).status(),413);pass('Image content validation rejects SVG spoofing and oversized payloads');
 const state=await board(ownerContext);await post(ownerContext,{action:'columns',revision:state.revision,columns:state.columns.filter(c=>c.id!=='new')},400);pass('A populated column cannot be removed and strand its cards');
 await page.getByRole('button',{name:'Refresh requests',exact:true}).click();await page.getByRole('button',{name:'Open request: '+title,exact:true}).click();await page.getByLabel('Request title',{exact:true}).fill(title+' unsaved');await page.keyboard.press('Escape');await page.getByRole('alertdialog').getByRole('button',{name:'Keep editing',exact:true}).click();assert.equal(await page.getByLabel('Request title',{exact:true}).inputValue(),title+' unsaved');await page.getByRole('button',{name:'Cancel',exact:true}).click();await page.getByRole('alertdialog').getByRole('button',{name:'Discard changes',exact:true}).click();await page.getByRole('dialog').waitFor({state:'hidden'});pass('Discard protection keeps unsaved edits until explicitly discarded');
 await page.getByRole('button',{name:'Open request: '+title,exact:true}).click();const pictureName=(await board(ownerContext)).requests.find(c=>c.id===saved.id).images[0].name;await page.getByRole('button',{name:'Remove image '+pictureName,exact:true}).click();await page.waitForFunction(()=>document.querySelectorAll('.request-images figure').length===1);assert.equal((await ownerContext.request.get(saved.images[0].url)).status(),404);await page.getByRole('button',{name:'Archive request',exact:true}).click();await page.getByRole('alertdialog').getByRole('button',{name:'Archive request',exact:true}).click();await page.getByRole('alertdialog').waitFor({state:'hidden'});await page.getByRole('dialog').waitFor({state:'hidden'});assert.ok(!(await board(ownerContext)).requests.some(c=>c.id===saved.id));assert.equal((await ownerContext.request.get(saved.images[1].url)).status(),404);pass('Image removal deletes access and archived requests leave the board');assert.deepEqual(errors,[]);pass('Requests journey has no browser runtime errors');
} finally {
 await browser.close();
 if(tenantId){for(const id of created.cards){const objects=await service.storage.from(bucket).list(tenantId+'/'+id);if(!objects.error&&objects.data.length)assert.ifError((await service.storage.from(bucket).remove(objects.data.map(o=>tenantId+'/'+id+'/'+o.name))).error);}if(created.cards.length)assert.ifError((await service.from('workspace_requests').delete().eq('tenant_id',tenantId).in('id',created.cards)).error);
  if(!hadBoard){const remaining=await service.from('workspace_requests').select('id').eq('tenant_id',tenantId);if(!remaining.data?.length)assert.ifError((await service.from('request_boards').delete().eq('tenant_id',tenantId)).error);}else if(original){assert.ifError((await service.from('request_boards').update({columns:original.columns}).eq('tenant_id',tenantId)).error);}
 }
 for(const id of created.users){assert.ifError((await service.from('workspace_members').delete().eq('id',id)).error);assert.ifError((await service.auth.admin.deleteUser(id)).error);}
}
console.log(checks+' Requests checks passed');
