// Real editable settings, signed-out attempts and saved results; loopback only.
import {chromium} from 'playwright';
import AxeBuilder from '@axe-core/playwright';
import assert from 'node:assert/strict';
import {mkdirSync} from 'node:fs';
const base='http://127.0.0.1:5173', browser=await chromium.launch({executablePath:process.env.CHROMIUM_PATH||'/usr/bin/chromium'});
let checks=0;const pass=name=>{checks++;console.log('PASS:',name);};
async function api(page,body){const r=await page.evaluate(async body=>{const r=await fetch('/api/admin',{method:body?'POST':'GET',headers:{'Content-Type':'application/json'},...(body?{body:JSON.stringify(body)}:{})});return {status:r.status,data:await r.json()};},body);assert.equal(r.status,200,JSON.stringify(r.data));return r.data;}
async function audit(page,name){const r=await new AxeBuilder({page}).withTags(['wcag2a','wcag2aa','wcag21aa']).analyze();assert.deepEqual(r.violations.map(v=>({id:v.id,nodes:v.nodes.map(n=>n.failureSummary)})),[]);pass(name);}
async function select(page,label,option){await page.getByLabel(label,{exact:true}).click();await page.getByRole('option',{name:option,exact:true}).click();}
mkdirSync('test-results/settings',{recursive:true});
try {
 const adminContext=await browser.newContext(),admin=await adminContext.newPage();await admin.goto(base+'/login');await admin.getByLabel('Email address',{exact:true}).fill('recruiter@qa.invalid');await admin.getByLabel('Password',{exact:true}).fill('Local-QA-Only-57!Password');await admin.getByRole('button',{name:'Sign in',exact:true}).click();await admin.getByRole('heading',{name:'Assessments',exact:true}).waitFor();
 assert.equal(await admin.getByText('Standard assessments are limited to 10 minutes.',{exact:false}).count(),0);assert.equal(await admin.getByText('People make the decision',{exact:true}).count(),0);pass('repeated policy explanations removed');
 await admin.getByRole('button',{name:'Module library',exact:true}).click();await admin.getByRole('button',{name:'Create module',exact:true}).first().click();await admin.getByRole('dialog').getByRole('button',{name:'Typing',exact:true}).click();
 const title='SETTINGS SYNTHETIC Editable typing '+Date.now();await admin.getByLabel('Module title',{exact:true}).fill(title);await admin.getByLabel('Time limit (seconds)',{exact:true}).fill('900');await select(admin,'Typing measurement','Separate speed and accuracy');await admin.getByLabel('Typing duration (seconds)',{exact:true}).fill('15');await admin.getByLabel('Allow early finish when the full passage is correct',{exact:true}).uncheck();await admin.getByLabel('Allow pasting into the typing response',{exact:true}).check();await admin.getByRole('button',{name:'Save module',exact:true}).click();await admin.getByRole('heading',{name:'Module editor',exact:true}).waitFor({state:'hidden'});
 const library=(await api(admin)).library.find(r=>r.module.title===title);assert.equal(library.module.typingSeconds,15);assert.equal(library.module.seconds,900);assert.equal(library.module.allowPaste,true);assert.equal(library.module.finishTypingEarly,false);pass('editable typing rules persist in module library');
 await admin.locator('.library-card').filter({has: admin.getByRole('heading', { name: title, exact: true })}).getByRole('button',{name:'Build assessment',exact:true}).click();const assessmentTitle='SETTINGS SYNTHETIC Longer assessment '+Date.now();await admin.getByLabel('Assessment title',{exact:true}).fill(assessmentTitle);await select(admin,'Candidate timing','Separate section timers');await admin.getByLabel('Module title',{exact:true}).fill(title);assert.equal(await admin.getByLabel('Candidate timing',{exact:true}).innerText(),'Separate section timers');pass('editing measured module preserves sequential timer choice');await select(admin,'Candidate timing','Shared work timer');await admin.getByLabel('Work timer (seconds)',{exact:true}).fill('1200');await admin.getByText('Candidate settings',{exact:true}).click();await admin.getByLabel('Show one question at a time',{exact:true}).uncheck();await admin.getByLabel('Allow going back to earlier answers',{exact:true}).check();await admin.getByLabel('Link expiry (days)',{exact:true}).fill('3');await admin.getByLabel('Allowed tools and assistance',{exact:true}).fill('Use the supplied material.');await admin.getByLabel('Candidate data-use notice',{exact:true}).fill('Responses are reviewed by our team.');await audit(admin,'desktop settings accessibility');await admin.screenshot({path:'test-results/settings/builder.png',fullPage:true});await admin.getByRole('button',{name:'Save & mark ready',exact:true}).click();await admin.getByRole('heading',{name:'Assessment builder',exact:true}).waitFor({state:'hidden'});
 const assessment=(await api(admin)).assessments.find(a=>a.title===assessmentTitle);assert.equal(assessment.config.workSeconds,1200);assert.equal(assessment.config.linkExpiryDays,3);pass('20-minute assessment saves without old cap');
 await admin.locator('.assessment-table tbody tr').filter({has: admin.getByText(assessmentTitle, {exact:true})}).getByRole('button',{name:'Create candidate link',exact:true}).click();await admin.getByLabel('Candidate name or reference',{exact:true}).fill('SETTINGS SYNTHETIC Candidate');await admin.getByRole('dialog').getByRole('button',{name:'Create candidate link',exact:true}).click();const url=await admin.getByLabel('Candidate assessment link',{exact:true}).inputValue(), token=url.split('/').at(-1);const assignment=(await api(admin)).attempts.find(a=>a.assessmentId===assessment.id);assert.equal(assignment.expiresAt-assignment.createdAt,3*86400000);pass('candidate link uses saved expiry');
 const context=await browser.newContext({viewport:{width:390,height:844},permissions:['clipboard-read','clipboard-write']}),candidate=await context.newPage();await candidate.goto(url);await candidate.getByRole('button',{name:'Start assessment',exact:true}).waitFor();assert.equal(await candidate.getByText('Use the supplied material.',{exact:true}).count(),1);await audit(candidate,'mobile configured welcome accessibility');await candidate.getByRole('checkbox').check();await candidate.getByRole('button',{name:'Start assessment',exact:true}).click();await candidate.getByRole('button',{name:'Start 15-second task',exact:true}).click();const input=candidate.getByLabel('Your typed copy',{exact:true});await input.waitFor();const view=await candidate.evaluate(async token=>(await fetch('/api/candidate?token='+token)).json(),token);assert.equal(view.answer.typing.deadline-view.answer.typing.startedAt,15000);pass('signed-out attempt uses custom typing duration');
 await candidate.evaluate(text=>navigator.clipboard.writeText(text),library.module.passage);await input.focus();await input.press('Control+v');await candidate.waitForFunction(text=>document.querySelector('textarea[aria-label="Your typed copy"]').value===text,library.module.passage);assert.equal(await candidate.getByRole('button',{name:'Finish complete passage early',exact:true}).count(),0);const rejected=await candidate.evaluate(async ({token,revision,text})=>{const r=await fetch('/api/candidate',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({token,revision,action:'typing-finish',answer:{text}})});return r.status;},{token,revision:view.revision,text:library.module.passage});assert.equal(rejected,400);pass('paste allowed and disabled early completion enforced by server');await audit(candidate,'mobile custom typing accessibility');
 await candidate.getByText('Typing saved and locked.',{exact:false}).waitFor({timeout:25000});await candidate.getByRole('button',{name:'Review answers',exact:true}).click();await candidate.getByRole('button',{name:'Submit assessment',exact:true}).click();await candidate.getByRole('button',{name:'Confirm submission',exact:true}).click();await candidate.getByRole('heading',{name:'Your responses have been submitted',exact:true}).waitFor();const completed=(await api(admin)).attempts.find(a=>a.id===assignment.id);assert.equal(completed.result.modules[0].seconds,15);assert.equal(completed.result.modules[0].accuracy,100);pass('results use configured server duration and saved text');await context.close();
 const sequential=structuredClone(assessment);sequential.id='';sequential.revision=0;sequential.title='SETTINGS SYNTHETIC Sequential custom typing';sequential.config.flexible=false;sequential.config.toolPolicy='';sequential.config.notice='';sequential.modules[0].typingSeconds=30;sequential.modules[0].finishTypingEarly=true;const saved=await api(admin,{action:'save',assessment:sequential}),link=await api(admin,{action:'link',id:saved.id,alias:'SETTINGS SYNTHETIC Sequential candidate'});assert.equal((await api(admin)).assessments.find(a=>a.id===saved.id).config.flexible,false);pass('sequential timer choice survives save and reload');
 const seqContext=await browser.newContext(),seq=await seqContext.newPage();await seq.goto(base+link.path);await seq.getByRole('checkbox').check();await seq.getByRole('button',{name:'Start assessment',exact:true}).click();await seq.getByLabel('Your typed copy',{exact:true}).waitFor();const started=await seq.evaluate(async token=>(await fetch('/api/candidate?token='+token)).json(),link.path.split('/').at(-1));assert.equal(started.sectionDeadline-started.startedAt,30000);assert.equal(started.seconds,30);assert.equal(started.sections[0].seconds,30);assert.equal(started.deadline-started.startedAt,30000);await seq.getByLabel('Your typed copy',{exact:true}).fill(sequential.modules[0].passage);await seq.getByRole('button',{name:'Submit assessment',exact:true}).click();await seq.getByRole('alertdialog').getByRole('button',{name:'Submit assessment',exact:true}).click();await seq.getByRole('heading',{name:/You’re all done/}).waitFor();const result=(await api(admin)).attempts.find(a=>a.id===link.id);assert.ok(result.result.modules[0].seconds>0&&result.result.modules[0].seconds<30);assert.equal(result.result.modules[0].accuracy,100);pass('sequential custom duration and optional early completion record actual time');
 const edited=(await api(admin)).assessments.find(a=>a.id===assessment.id);edited.config.workSeconds=1800;edited.modules[0].typingSeconds=45;edited.modules[0].allowPaste=false;await api(admin,{action:'save',assessment:edited});const frozen=(await api(admin)).attempts.find(a=>a.id===assignment.id);assert.equal(frozen.config.workSeconds,1200);assert.equal(frozen.modules[0].typingSeconds,15);assert.equal(frozen.modules[0].allowPaste,true);assert.deepEqual(frozen.result,completed.result);pass('template edits preserve existing saved results');await seqContext.close();
} finally {await browser.close();}
console.log(checks+' configurable settings checks passed');
