// Imported only by the authenticated admin API. Never bundle answer keys into public client assets.
import { ModuleKind, TestModule, Assessment, kindLabels } from './assessment';
const uid = () => crypto.randomUUID();
export function template(kind: ModuleKind): TestModule {
    const base = { id: uid(), kind, title: kindLabels[kind], seconds: 60, instructions: 'Choose the best answer for each question.' };
    if (kind === 'spelling')
        return { ...base, context: 'Case notes: Order R-184 was returned on Monday. The £48 refund was issued on Tuesday and takes 3–5 working days to reach the original payment method. No replacement has been dispatched.', questions: [
            { id: uid(), prompt: 'Which update accurately reflects the case notes?', options: ['Your £48 refund was issued on Tuesday to your original payment method. Please allow 3–5 working days for it to arrive.', 'Your £48 refund arrived on Tuesday and your replacement is on its way.', 'We will issue your refund when the replacement is delivered.'], correct: 0, explanation: 'Only the first message preserves the amount, issue date, payment method and processing window without inventing a replacement.' },
            { id: uid(), prompt: 'A colleague writes: “Your refund is definately guaranteed tomorrow.” Which revision is accurate and professionally written?', options: ['Your refund is definitely guaranteed tomorrow.', 'Your refund has been issued. Please allow 3–5 working days for it to reach your original payment method.', 'Your refund should of arrived; contact your bank instead.'], correct: 1, explanation: 'Correct spelling alone is insufficient: the supplied policy does not guarantee arrival tomorrow. The second reply is accurate and clear.' }
        ] };
    if (kind === 'grammar')
        return { ...base, seconds: 75, context: 'Queue policy: handle active account-security risks first, then time-sensitive service interruptions, then routine requests. Do not request passwords or verification codes. Keep updates factual and own the next action.', questions: [
            { id: uid(), prompt: 'Three tickets arrive: an unexpected password-change notification, a delivery-address change needed before dispatch in 30 minutes, and a request for a receipt. Which should you handle first?', options: ['The receipt, because it is the quickest to close.', 'The address change, because the customer is upset.', 'The unexpected password change: it may be an active security risk.'], correct: 2, explanation: 'The queue policy puts active account-security risks before dispatch deadlines and routine requests.' },
            { id: uid(), prompt: 'A customer posts a verification code in chat while reporting an unexpected password change. What is the best response?', options: ['Use the code to log in and check the account.', 'Ask them not to share codes, follow the approved secure recovery process and escalate the risk.', 'Close the chat because they have breached security policy.'], correct: 1, explanation: 'Protect credentials, retain ownership and use the secure recovery process; neither logging in as the customer nor abandoning them is appropriate.' }
        ] };
    if (kind === 'typing')
        return { ...base, instructions: 'Copy the passage accurately.', targetWpm: 45, passage: 'Thank you for getting in touch about your order. I understand that you were expecting the parcel yesterday, and I am sorry that the delay has disrupted your plans. I have checked the tracking information and can see that the courier has received the parcel. The next update should appear within one working day. If the tracking has not changed by tomorrow afternoon, please reply to this message and we will contact the courier for you. You do not need to place another order or share your payment details. I will keep the case open until we have a clear update. When the parcel arrives, please check that all the items are included. If anything is missing or damaged, let us know within seven days and include your order reference. We can then explain the available options and help you choose the next step. Our support team is available from nine in the morning until five in the afternoon on working days. We appreciate your patience while we investigate and will make sure that you receive a useful update. Please keep the original packaging until we have resolved the case, as the courier may ask for a photograph of the label. We will never ask you to send your full card number, password or a verification code in a support message. Your account details remain protected throughout the investigation. Thank you again for giving us the opportunity to help.' };
    if (kind === 'problem')
        return { ...base, seconds: 105, context: 'Delivery policy: investigate after 2 working days without a tracking update. Check the order reference, dispatch date and tracking events, then contact the courier; allow 1 working day for a reply. Offer a replacement only after the courier confirms loss. Never request passwords or full card details.\nCase: Tracking has not changed for 3 working days. The customer needs the parcel as a gift tomorrow and asks for an immediate replacement.', questions: [
            { id: uid(), prompt: 'What should you do first to investigate this case?', options: ['Check the order and tracking history, then contact the courier and arrange an update within 1 working day.', 'Dispatch a replacement immediately because the parcel is a gift.', 'Tell the customer to wait without checking the order.'], correct: 0, explanation: 'The delay meets the investigation threshold. Verify the case facts and contact the courier before any replacement commitment.' },
            { id: uid(), prompt: 'The courier says the parcel is still at its depot and cannot confirm a delivery date. What can you tell the customer?', options: ['It will definitely arrive tomorrow.', 'A replacement has already been approved.', 'The courier has located the parcel, but has not confirmed a delivery date. Explain the next follow-up without guaranteeing tomorrow.'], correct: 2, explanation: 'Located at a depot is not confirmed loss. Communicate the evidence accurately and avoid an unsupported delivery or replacement promise.' },
            { id: uid(), prompt: 'The courier subsequently confirms the parcel is lost. Which next step follows the policy?', options: ['Request the full payment-card number to authorise a replacement.', 'Offer a replacement using the verified order details, without requesting sensitive credentials.', 'Begin the same investigation again before offering anything.'], correct: 1, explanation: 'Confirmed loss meets the replacement condition. The verified order is sufficient; sensitive credentials are never required.' }
        ] };
    return { ...base, seconds: 240, instructions: 'Write the reply you would send to the customer. Aim for 80–140 words. The reviewer will assess accuracy, empathy, clarity and next steps.', context: 'Customer message\n“I paid for delivery and my parcel still isn’t here. Tracking hasn’t moved for three working days. This was a gift and I’m really disappointed. Can you send another one today?”\n\nPolicy\n• Investigate after 2 working days without a tracking update\n• Contact the courier first; allow 1 working day for a reply\n• A replacement is available only after the courier confirms the parcel is lost\n• Never request passwords or full payment-card details', prompt: 'Write a helpful reply that acknowledges the concern, explains what you can do now and sets a clear next step. Do not invent a refund or delivery guarantee.' };
}
export function defaultAssessment(): Assessment { return { id: uid(), title: 'Customer support essentials', description: 'A short, practical work sample for written customer-service roles.', status: 'ready', modules: ['spelling', 'grammar', 'typing', 'problem', 'writing'].map(k => template(k as ModuleKind)), updatedAt: Date.now(), revision: 1 }; }
